//! The RunAnywhere SDK C ABI.
//!
//! `bindings.rs` is generated by scripts/build/gen-sys-bindings.sh from the
//! pinned kit's headers (see scripts/build/sys-bindings.h for the list) and is
//! committed; regenerate it on a kit bump. The private-pack overlay entry points
//! (NeuRT, QHexRT) are not in the public kit headers and are declared here.
//!
//! Everything in this module is raw FFI. Safe wrappers live next to their users
//! (e.g. `io::proto::ProtoBuffer`).

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]
#![allow(clippy::all)]

include!("bindings.rs");

#[cfg(wally_has_neurt)]
extern "C" {
    /// rac/plugin/rac_plugin_entry_neurt.h (NeuRT private pack): the plugin
    /// vtable; registering it also keeps the static archive linked.
    pub fn rac_plugin_entry_neurt() -> *const rac_engine_vtable_t;
}

#[cfg(wally_has_qhexrt)]
extern "C" {
    /// QHexRT private pack (Windows ARM64 only); no public header.
    pub fn rac_backend_qhexrt_register() -> rac_result_t;
}

// bindgen evaluates the kit's cast macros (`#define RAC_SUCCESS ((rac_result_t)0)`)
// through clang but types the plain ones as u32. These carry the C types, so
// callers compare and pass them without casts. The RAC_ERROR_* codes already
// come out as i32 == rac_result_t.
/// `RAC_SUCCESS`.
pub const SUCCESS: rac_result_t = RAC_SUCCESS as rac_result_t;
/// `RAC_TRUE`.
pub const TRUE: rac_bool_t = RAC_TRUE as rac_bool_t;
/// `RAC_FALSE`.
pub const FALSE: rac_bool_t = RAC_FALSE as rac_bool_t;
