// Generated by contracts/generate_console_binding.py from
// contracts/wally-cli-v1.openapi.json. DO NOT EDIT.
//
// Typed request and response models for the CLI's control-plane calls, so
// console.cpp neither builds a request body by hand nor reads a response
// field by name. Regenerate and commit whenever the pinned contract moves.
#ifndef WALLY_ACCOUNT_CONSOLE_CONTRACT_H
#define WALLY_ACCOUNT_CONSOLE_CONTRACT_H

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

#include <nlohmann/json.hpp>

namespace wally::account::contract {

// SHA-256 of contracts/wally-cli-v1.openapi.json this header was built from.
inline constexpr char kContractSha256[] = "40512a48d9a94d093ce5d9da9c9fc7984fabd90bb9bc61b2814fb58fc685e85f";

enum class ApiErrorCode {
    kInvalidRequest,
    kUnauthorized,
    kForbidden,
    kNotFound,
    kMethodNotAllowed,
    kConflict,
    kGone,
    kPayloadTooLarge,
    kRateLimited,
    kInternalError,
    kUpstreamUnavailable,
    kServiceUnavailable,
    kTimeout,
    kBadRequest,
    kControlPlaneOverloaded,
    kExpiredApiKey,
    kGatewayUnavailable,
    kIdempotencyKeyReused,
    kInsufficientCredit,
    kInvalidApiKey,
    kModelNotEntitled,
    kNotInCohort,
    kProvisioningUnavailable,
    kProxyRetired,
    kRevokedApiKey,
    kSignupMethodNotAllowed,
    kUpstreamContractViolation,
    kUserRateLimited,
    kGatewayNotConfigured,
    kGatewayTimeout,
    kGatewayProtocolError,
    kGatewayOperationPending,
    kReconciliationUnverified,
};

inline void from_json(const nlohmann::json& j, ApiErrorCode& value) {
    const std::string raw = j.get<std::string>();
    if (raw == "invalid_request") { value = ApiErrorCode::kInvalidRequest; return; }
    if (raw == "unauthorized") { value = ApiErrorCode::kUnauthorized; return; }
    if (raw == "forbidden") { value = ApiErrorCode::kForbidden; return; }
    if (raw == "not_found") { value = ApiErrorCode::kNotFound; return; }
    if (raw == "method_not_allowed") { value = ApiErrorCode::kMethodNotAllowed; return; }
    if (raw == "conflict") { value = ApiErrorCode::kConflict; return; }
    if (raw == "gone") { value = ApiErrorCode::kGone; return; }
    if (raw == "payload_too_large") { value = ApiErrorCode::kPayloadTooLarge; return; }
    if (raw == "rate_limited") { value = ApiErrorCode::kRateLimited; return; }
    if (raw == "internal_error") { value = ApiErrorCode::kInternalError; return; }
    if (raw == "upstream_unavailable") { value = ApiErrorCode::kUpstreamUnavailable; return; }
    if (raw == "service_unavailable") { value = ApiErrorCode::kServiceUnavailable; return; }
    if (raw == "timeout") { value = ApiErrorCode::kTimeout; return; }
    if (raw == "bad_request") { value = ApiErrorCode::kBadRequest; return; }
    if (raw == "control_plane_overloaded") { value = ApiErrorCode::kControlPlaneOverloaded; return; }
    if (raw == "expired_api_key") { value = ApiErrorCode::kExpiredApiKey; return; }
    if (raw == "gateway_unavailable") { value = ApiErrorCode::kGatewayUnavailable; return; }
    if (raw == "idempotency_key_reused") { value = ApiErrorCode::kIdempotencyKeyReused; return; }
    if (raw == "insufficient_credit") { value = ApiErrorCode::kInsufficientCredit; return; }
    if (raw == "invalid_api_key") { value = ApiErrorCode::kInvalidApiKey; return; }
    if (raw == "model_not_entitled") { value = ApiErrorCode::kModelNotEntitled; return; }
    if (raw == "not_in_cohort") { value = ApiErrorCode::kNotInCohort; return; }
    if (raw == "provisioning_unavailable") { value = ApiErrorCode::kProvisioningUnavailable; return; }
    if (raw == "proxy_retired") { value = ApiErrorCode::kProxyRetired; return; }
    if (raw == "revoked_api_key") { value = ApiErrorCode::kRevokedApiKey; return; }
    if (raw == "signup_method_not_allowed") { value = ApiErrorCode::kSignupMethodNotAllowed; return; }
    if (raw == "upstream_contract_violation") { value = ApiErrorCode::kUpstreamContractViolation; return; }
    if (raw == "user_rate_limited") { value = ApiErrorCode::kUserRateLimited; return; }
    if (raw == "gateway_not_configured") { value = ApiErrorCode::kGatewayNotConfigured; return; }
    if (raw == "gateway_timeout") { value = ApiErrorCode::kGatewayTimeout; return; }
    if (raw == "gateway_protocol_error") { value = ApiErrorCode::kGatewayProtocolError; return; }
    if (raw == "gateway_operation_pending") { value = ApiErrorCode::kGatewayOperationPending; return; }
    if (raw == "reconciliation_unverified") { value = ApiErrorCode::kReconciliationUnverified; return; }
    throw nlohmann::json::type_error::create(302, "unknown ApiErrorCode: " + raw, &j);
}

inline void to_json(nlohmann::json& j, const ApiErrorCode& value) {
    switch (value) {
        case ApiErrorCode::kInvalidRequest: j = "invalid_request"; return;
        case ApiErrorCode::kUnauthorized: j = "unauthorized"; return;
        case ApiErrorCode::kForbidden: j = "forbidden"; return;
        case ApiErrorCode::kNotFound: j = "not_found"; return;
        case ApiErrorCode::kMethodNotAllowed: j = "method_not_allowed"; return;
        case ApiErrorCode::kConflict: j = "conflict"; return;
        case ApiErrorCode::kGone: j = "gone"; return;
        case ApiErrorCode::kPayloadTooLarge: j = "payload_too_large"; return;
        case ApiErrorCode::kRateLimited: j = "rate_limited"; return;
        case ApiErrorCode::kInternalError: j = "internal_error"; return;
        case ApiErrorCode::kUpstreamUnavailable: j = "upstream_unavailable"; return;
        case ApiErrorCode::kServiceUnavailable: j = "service_unavailable"; return;
        case ApiErrorCode::kTimeout: j = "timeout"; return;
        case ApiErrorCode::kBadRequest: j = "bad_request"; return;
        case ApiErrorCode::kControlPlaneOverloaded: j = "control_plane_overloaded"; return;
        case ApiErrorCode::kExpiredApiKey: j = "expired_api_key"; return;
        case ApiErrorCode::kGatewayUnavailable: j = "gateway_unavailable"; return;
        case ApiErrorCode::kIdempotencyKeyReused: j = "idempotency_key_reused"; return;
        case ApiErrorCode::kInsufficientCredit: j = "insufficient_credit"; return;
        case ApiErrorCode::kInvalidApiKey: j = "invalid_api_key"; return;
        case ApiErrorCode::kModelNotEntitled: j = "model_not_entitled"; return;
        case ApiErrorCode::kNotInCohort: j = "not_in_cohort"; return;
        case ApiErrorCode::kProvisioningUnavailable: j = "provisioning_unavailable"; return;
        case ApiErrorCode::kProxyRetired: j = "proxy_retired"; return;
        case ApiErrorCode::kRevokedApiKey: j = "revoked_api_key"; return;
        case ApiErrorCode::kSignupMethodNotAllowed: j = "signup_method_not_allowed"; return;
        case ApiErrorCode::kUpstreamContractViolation: j = "upstream_contract_violation"; return;
        case ApiErrorCode::kUserRateLimited: j = "user_rate_limited"; return;
        case ApiErrorCode::kGatewayNotConfigured: j = "gateway_not_configured"; return;
        case ApiErrorCode::kGatewayTimeout: j = "gateway_timeout"; return;
        case ApiErrorCode::kGatewayProtocolError: j = "gateway_protocol_error"; return;
        case ApiErrorCode::kGatewayOperationPending: j = "gateway_operation_pending"; return;
        case ApiErrorCode::kReconciliationUnverified: j = "reconciliation_unverified"; return;
    }
}

enum class CliClient {
    kRcli,
};

inline void from_json(const nlohmann::json& j, CliClient& value) {
    const std::string raw = j.get<std::string>();
    if (raw == "rcli") { value = CliClient::kRcli; return; }
    throw nlohmann::json::type_error::create(302, "unknown CliClient: " + raw, &j);
}

inline void to_json(nlohmann::json& j, const CliClient& value) {
    switch (value) {
        case CliClient::kRcli: j = "rcli"; return;
    }
}

enum class CliPlan {
    kBeta,
};

inline void from_json(const nlohmann::json& j, CliPlan& value) {
    const std::string raw = j.get<std::string>();
    if (raw == "beta") { value = CliPlan::kBeta; return; }
    throw nlohmann::json::type_error::create(302, "unknown CliPlan: " + raw, &j);
}

inline void to_json(nlohmann::json& j, const CliPlan& value) {
    switch (value) {
        case CliPlan::kBeta: j = "beta"; return;
    }
}

enum class CliUsageWindowLabel {
    k1h,
    k24h,
};

inline void from_json(const nlohmann::json& j, CliUsageWindowLabel& value) {
    const std::string raw = j.get<std::string>();
    if (raw == "1h") { value = CliUsageWindowLabel::k1h; return; }
    if (raw == "24h") { value = CliUsageWindowLabel::k24h; return; }
    throw nlohmann::json::type_error::create(302, "unknown CliUsageWindowLabel: " + raw, &j);
}

inline void to_json(nlohmann::json& j, const CliUsageWindowLabel& value) {
    switch (value) {
        case CliUsageWindowLabel::k1h: j = "1h"; return;
        case CliUsageWindowLabel::k24h: j = "24h"; return;
    }
}

enum class ErrorCode {
    kBadRequest,
    kNotFound,
    kPayloadTooLarge,
    kUnprocessable,
    kInvalidApiKey,
    kExpiredApiKey,
    kRevokedApiKey,
    kInsufficientCredit,
    kAccountFrozen,
    kModelNotEntitled,
    kNotInCohort,
    kUserRateLimited,
    kRequestCancelled,
    kQuotaExceeded,
    kCapacityExceeded,
    kIdempotencyKeyReused,
    kUnsupportedEndpoint,
    kProxyRetired,
    kGatewayUnavailable,
    kControlPlaneOverloaded,
    kCreditGateUnavailable,
    kUpstreamContractViolation,
    kUnattributedKey,
    kInternal,
    kBadGateway,
    kDraining,
    kSpoolUnhealthy,
    kCold,
    kTimeout,
};

inline void from_json(const nlohmann::json& j, ErrorCode& value) {
    const std::string raw = j.get<std::string>();
    if (raw == "bad_request") { value = ErrorCode::kBadRequest; return; }
    if (raw == "not_found") { value = ErrorCode::kNotFound; return; }
    if (raw == "payload_too_large") { value = ErrorCode::kPayloadTooLarge; return; }
    if (raw == "unprocessable") { value = ErrorCode::kUnprocessable; return; }
    if (raw == "invalid_api_key") { value = ErrorCode::kInvalidApiKey; return; }
    if (raw == "expired_api_key") { value = ErrorCode::kExpiredApiKey; return; }
    if (raw == "revoked_api_key") { value = ErrorCode::kRevokedApiKey; return; }
    if (raw == "insufficient_credit") { value = ErrorCode::kInsufficientCredit; return; }
    if (raw == "account_frozen") { value = ErrorCode::kAccountFrozen; return; }
    if (raw == "model_not_entitled") { value = ErrorCode::kModelNotEntitled; return; }
    if (raw == "not_in_cohort") { value = ErrorCode::kNotInCohort; return; }
    if (raw == "user_rate_limited") { value = ErrorCode::kUserRateLimited; return; }
    if (raw == "request_cancelled") { value = ErrorCode::kRequestCancelled; return; }
    if (raw == "quota_exceeded") { value = ErrorCode::kQuotaExceeded; return; }
    if (raw == "capacity_exceeded") { value = ErrorCode::kCapacityExceeded; return; }
    if (raw == "idempotency_key_reused") { value = ErrorCode::kIdempotencyKeyReused; return; }
    if (raw == "unsupported_endpoint") { value = ErrorCode::kUnsupportedEndpoint; return; }
    if (raw == "proxy_retired") { value = ErrorCode::kProxyRetired; return; }
    if (raw == "gateway_unavailable") { value = ErrorCode::kGatewayUnavailable; return; }
    if (raw == "control_plane_overloaded") { value = ErrorCode::kControlPlaneOverloaded; return; }
    if (raw == "credit_gate_unavailable") { value = ErrorCode::kCreditGateUnavailable; return; }
    if (raw == "upstream_contract_violation") { value = ErrorCode::kUpstreamContractViolation; return; }
    if (raw == "unattributed_key") { value = ErrorCode::kUnattributedKey; return; }
    if (raw == "internal") { value = ErrorCode::kInternal; return; }
    if (raw == "bad_gateway") { value = ErrorCode::kBadGateway; return; }
    if (raw == "draining") { value = ErrorCode::kDraining; return; }
    if (raw == "spool_unhealthy") { value = ErrorCode::kSpoolUnhealthy; return; }
    if (raw == "cold") { value = ErrorCode::kCold; return; }
    if (raw == "timeout") { value = ErrorCode::kTimeout; return; }
    throw nlohmann::json::type_error::create(302, "unknown ErrorCode: " + raw, &j);
}

inline void to_json(nlohmann::json& j, const ErrorCode& value) {
    switch (value) {
        case ErrorCode::kBadRequest: j = "bad_request"; return;
        case ErrorCode::kNotFound: j = "not_found"; return;
        case ErrorCode::kPayloadTooLarge: j = "payload_too_large"; return;
        case ErrorCode::kUnprocessable: j = "unprocessable"; return;
        case ErrorCode::kInvalidApiKey: j = "invalid_api_key"; return;
        case ErrorCode::kExpiredApiKey: j = "expired_api_key"; return;
        case ErrorCode::kRevokedApiKey: j = "revoked_api_key"; return;
        case ErrorCode::kInsufficientCredit: j = "insufficient_credit"; return;
        case ErrorCode::kAccountFrozen: j = "account_frozen"; return;
        case ErrorCode::kModelNotEntitled: j = "model_not_entitled"; return;
        case ErrorCode::kNotInCohort: j = "not_in_cohort"; return;
        case ErrorCode::kUserRateLimited: j = "user_rate_limited"; return;
        case ErrorCode::kRequestCancelled: j = "request_cancelled"; return;
        case ErrorCode::kQuotaExceeded: j = "quota_exceeded"; return;
        case ErrorCode::kCapacityExceeded: j = "capacity_exceeded"; return;
        case ErrorCode::kIdempotencyKeyReused: j = "idempotency_key_reused"; return;
        case ErrorCode::kUnsupportedEndpoint: j = "unsupported_endpoint"; return;
        case ErrorCode::kProxyRetired: j = "proxy_retired"; return;
        case ErrorCode::kGatewayUnavailable: j = "gateway_unavailable"; return;
        case ErrorCode::kControlPlaneOverloaded: j = "control_plane_overloaded"; return;
        case ErrorCode::kCreditGateUnavailable: j = "credit_gate_unavailable"; return;
        case ErrorCode::kUpstreamContractViolation: j = "upstream_contract_violation"; return;
        case ErrorCode::kUnattributedKey: j = "unattributed_key"; return;
        case ErrorCode::kInternal: j = "internal"; return;
        case ErrorCode::kBadGateway: j = "bad_gateway"; return;
        case ErrorCode::kDraining: j = "draining"; return;
        case ErrorCode::kSpoolUnhealthy: j = "spool_unhealthy"; return;
        case ErrorCode::kCold: j = "cold"; return;
        case ErrorCode::kTimeout: j = "timeout"; return;
    }
}

enum class ErrorType {
    kInvalidRequestError,
    kAuthenticationError,
    kPermissionError,
    kRateLimitError,
    kQuota,
    kCapacity,
    kServerError,
    kTimeout,
};

inline void from_json(const nlohmann::json& j, ErrorType& value) {
    const std::string raw = j.get<std::string>();
    if (raw == "invalid_request_error") { value = ErrorType::kInvalidRequestError; return; }
    if (raw == "authentication_error") { value = ErrorType::kAuthenticationError; return; }
    if (raw == "permission_error") { value = ErrorType::kPermissionError; return; }
    if (raw == "rate_limit_error") { value = ErrorType::kRateLimitError; return; }
    if (raw == "quota") { value = ErrorType::kQuota; return; }
    if (raw == "capacity") { value = ErrorType::kCapacity; return; }
    if (raw == "server_error") { value = ErrorType::kServerError; return; }
    if (raw == "timeout") { value = ErrorType::kTimeout; return; }
    throw nlohmann::json::type_error::create(302, "unknown ErrorType: " + raw, &j);
}

inline void to_json(nlohmann::json& j, const ErrorType& value) {
    switch (value) {
        case ErrorType::kInvalidRequestError: j = "invalid_request_error"; return;
        case ErrorType::kAuthenticationError: j = "authentication_error"; return;
        case ErrorType::kPermissionError: j = "permission_error"; return;
        case ErrorType::kRateLimitError: j = "rate_limit_error"; return;
        case ErrorType::kQuota: j = "quota"; return;
        case ErrorType::kCapacity: j = "capacity"; return;
        case ErrorType::kServerError: j = "server_error"; return;
        case ErrorType::kTimeout: j = "timeout"; return;
    }
}

enum class Harness {
    kClaudeCode,
    kOpencode,
    kHermes,
    kCursor,
    kContinue,
    kAider,
    kCline,
    kRoo,
    kZed,
    kOpenaiSdk,
    kLangchain,
    kLlamaindex,
    kCurl,
    kConsole,
    kPlayground,
    kRcli,
    kSdk,
    kUnknown,
};

inline void from_json(const nlohmann::json& j, Harness& value) {
    const std::string raw = j.get<std::string>();
    if (raw == "claude_code") { value = Harness::kClaudeCode; return; }
    if (raw == "opencode") { value = Harness::kOpencode; return; }
    if (raw == "hermes") { value = Harness::kHermes; return; }
    if (raw == "cursor") { value = Harness::kCursor; return; }
    if (raw == "continue") { value = Harness::kContinue; return; }
    if (raw == "aider") { value = Harness::kAider; return; }
    if (raw == "cline") { value = Harness::kCline; return; }
    if (raw == "roo") { value = Harness::kRoo; return; }
    if (raw == "zed") { value = Harness::kZed; return; }
    if (raw == "openai_sdk") { value = Harness::kOpenaiSdk; return; }
    if (raw == "langchain") { value = Harness::kLangchain; return; }
    if (raw == "llamaindex") { value = Harness::kLlamaindex; return; }
    if (raw == "curl") { value = Harness::kCurl; return; }
    if (raw == "console") { value = Harness::kConsole; return; }
    if (raw == "playground") { value = Harness::kPlayground; return; }
    if (raw == "rcli") { value = Harness::kRcli; return; }
    if (raw == "sdk") { value = Harness::kSdk; return; }
    if (raw == "unknown") { value = Harness::kUnknown; return; }
    throw nlohmann::json::type_error::create(302, "unknown Harness: " + raw, &j);
}

inline void to_json(nlohmann::json& j, const Harness& value) {
    switch (value) {
        case Harness::kClaudeCode: j = "claude_code"; return;
        case Harness::kOpencode: j = "opencode"; return;
        case Harness::kHermes: j = "hermes"; return;
        case Harness::kCursor: j = "cursor"; return;
        case Harness::kContinue: j = "continue"; return;
        case Harness::kAider: j = "aider"; return;
        case Harness::kCline: j = "cline"; return;
        case Harness::kRoo: j = "roo"; return;
        case Harness::kZed: j = "zed"; return;
        case Harness::kOpenaiSdk: j = "openai_sdk"; return;
        case Harness::kLangchain: j = "langchain"; return;
        case Harness::kLlamaindex: j = "llamaindex"; return;
        case Harness::kCurl: j = "curl"; return;
        case Harness::kConsole: j = "console"; return;
        case Harness::kPlayground: j = "playground"; return;
        case Harness::kRcli: j = "rcli"; return;
        case Harness::kSdk: j = "sdk"; return;
        case Harness::kUnknown: j = "unknown"; return;
    }
}

enum class PollStatus {
    kPending,
    kApproved,
    kDenied,
    kExpired,
};

inline void from_json(const nlohmann::json& j, PollStatus& value) {
    const std::string raw = j.get<std::string>();
    if (raw == "pending") { value = PollStatus::kPending; return; }
    if (raw == "approved") { value = PollStatus::kApproved; return; }
    if (raw == "denied") { value = PollStatus::kDenied; return; }
    if (raw == "expired") { value = PollStatus::kExpired; return; }
    throw nlohmann::json::type_error::create(302, "unknown PollStatus: " + raw, &j);
}

inline void to_json(nlohmann::json& j, const PollStatus& value) {
    switch (value) {
        case PollStatus::kPending: j = "pending"; return;
        case PollStatus::kApproved: j = "approved"; return;
        case PollStatus::kDenied: j = "denied"; return;
        case PollStatus::kExpired: j = "expired"; return;
    }
}

struct ApiError {
    ApiErrorCode code;
    std::string message;
};

inline void from_json(const nlohmann::json& j, ApiError& value) {
    if (j.contains("code") && !j.at("code").is_null()) {
        value.code = j.at("code").get<ApiErrorCode>();
    } else {
        value.code = ApiErrorCode{};
    }
    if (j.contains("message") && !j.at("message").is_null()) {
        value.message = j.at("message").get<std::string>();
    } else {
        value.message = std::string{};
    }
}

inline void to_json(nlohmann::json& j, const ApiError& value) {
    j = nlohmann::json::object();
    j["code"] = value.code;
    j["message"] = value.message;
}

struct CancelRequestResponse {
    std::string request_id;
    std::string status;
};

inline void from_json(const nlohmann::json& j, CancelRequestResponse& value) {
    if (j.contains("request_id") && !j.at("request_id").is_null()) {
        value.request_id = j.at("request_id").get<std::string>();
    } else {
        value.request_id = std::string{};
    }
    if (j.contains("status") && !j.at("status").is_null()) {
        value.status = j.at("status").get<std::string>();
    } else {
        value.status = std::string{};
    }
}

inline void to_json(nlohmann::json& j, const CancelRequestResponse& value) {
    j = nlohmann::json::object();
    j["request_id"] = value.request_id;
    j["status"] = value.status;
}

struct CatalogModelResponse {
    std::int64_t cached_input_per_mtok;
    std::string display_name;
    std::string id;
    std::int64_t input_per_mtok;
    std::int64_t output_per_mtok;
};

inline void from_json(const nlohmann::json& j, CatalogModelResponse& value) {
    if (j.contains("cached_input_per_mtok") && !j.at("cached_input_per_mtok").is_null()) {
        value.cached_input_per_mtok = j.at("cached_input_per_mtok").get<std::int64_t>();
    } else {
        value.cached_input_per_mtok = std::int64_t{};
    }
    if (j.contains("display_name") && !j.at("display_name").is_null()) {
        value.display_name = j.at("display_name").get<std::string>();
    } else {
        value.display_name = std::string{};
    }
    if (j.contains("id") && !j.at("id").is_null()) {
        value.id = j.at("id").get<std::string>();
    } else {
        value.id = std::string{};
    }
    if (j.contains("input_per_mtok") && !j.at("input_per_mtok").is_null()) {
        value.input_per_mtok = j.at("input_per_mtok").get<std::int64_t>();
    } else {
        value.input_per_mtok = std::int64_t{};
    }
    if (j.contains("output_per_mtok") && !j.at("output_per_mtok").is_null()) {
        value.output_per_mtok = j.at("output_per_mtok").get<std::int64_t>();
    } else {
        value.output_per_mtok = std::int64_t{};
    }
}

inline void to_json(nlohmann::json& j, const CatalogModelResponse& value) {
    j = nlohmann::json::object();
    j["cached_input_per_mtok"] = value.cached_input_per_mtok;
    j["display_name"] = value.display_name;
    j["id"] = value.id;
    j["input_per_mtok"] = value.input_per_mtok;
    j["output_per_mtok"] = value.output_per_mtok;
}

struct CliPollRequest {
    std::string poll_secret;
    std::string request_code;
};

inline void from_json(const nlohmann::json& j, CliPollRequest& value) {
    if (j.contains("poll_secret") && !j.at("poll_secret").is_null()) {
        value.poll_secret = j.at("poll_secret").get<std::string>();
    } else {
        value.poll_secret = std::string{};
    }
    if (j.contains("request_code") && !j.at("request_code").is_null()) {
        value.request_code = j.at("request_code").get<std::string>();
    } else {
        value.request_code = std::string{};
    }
}

inline void to_json(nlohmann::json& j, const CliPollRequest& value) {
    j = nlohmann::json::object();
    j["poll_secret"] = value.poll_secret;
    j["request_code"] = value.request_code;
}

struct CliRefreshRequest {
    std::string refresh_token;
};

inline void from_json(const nlohmann::json& j, CliRefreshRequest& value) {
    if (j.contains("refresh_token") && !j.at("refresh_token").is_null()) {
        value.refresh_token = j.at("refresh_token").get<std::string>();
    } else {
        value.refresh_token = std::string{};
    }
}

inline void to_json(nlohmann::json& j, const CliRefreshRequest& value) {
    j = nlohmann::json::object();
    j["refresh_token"] = value.refresh_token;
}

struct CliStartRequest {
    CliClient client;
    std::string hostname;
};

inline void from_json(const nlohmann::json& j, CliStartRequest& value) {
    if (j.contains("client") && !j.at("client").is_null()) {
        value.client = j.at("client").get<CliClient>();
    } else {
        value.client = CliClient{};
    }
    if (j.contains("hostname") && !j.at("hostname").is_null()) {
        value.hostname = j.at("hostname").get<std::string>();
    } else {
        value.hostname = std::string{};
    }
}

inline void to_json(nlohmann::json& j, const CliStartRequest& value) {
    j = nlohmann::json::object();
    j["client"] = value.client;
    j["hostname"] = value.hostname;
}

struct CliStartResponse {
    std::int64_t expires_in;
    std::int64_t interval;
    std::string poll_secret;
    std::string request_code;
    std::string verification_url;
};

inline void from_json(const nlohmann::json& j, CliStartResponse& value) {
    if (j.contains("expires_in") && !j.at("expires_in").is_null()) {
        value.expires_in = j.at("expires_in").get<std::int64_t>();
    } else {
        value.expires_in = std::int64_t{};
    }
    if (j.contains("interval") && !j.at("interval").is_null()) {
        value.interval = j.at("interval").get<std::int64_t>();
    } else {
        value.interval = std::int64_t{};
    }
    if (j.contains("poll_secret") && !j.at("poll_secret").is_null()) {
        value.poll_secret = j.at("poll_secret").get<std::string>();
    } else {
        value.poll_secret = std::string{};
    }
    if (j.contains("request_code") && !j.at("request_code").is_null()) {
        value.request_code = j.at("request_code").get<std::string>();
    } else {
        value.request_code = std::string{};
    }
    if (j.contains("verification_url") && !j.at("verification_url").is_null()) {
        value.verification_url = j.at("verification_url").get<std::string>();
    } else {
        value.verification_url = std::string{};
    }
}

inline void to_json(nlohmann::json& j, const CliStartResponse& value) {
    j = nlohmann::json::object();
    j["expires_in"] = value.expires_in;
    j["interval"] = value.interval;
    j["poll_secret"] = value.poll_secret;
    j["request_code"] = value.request_code;
    j["verification_url"] = value.verification_url;
}

struct CliUsageEvent {
    std::int64_t cached_tokens;
    std::int64_t completion_tokens;
    std::int64_t cost_micros;
    std::optional<std::string> error_code;
    std::optional<Harness> harness;
    std::string model;
    std::int64_t prompt_tokens;
    std::string request_id;
    std::int64_t status_code;
    std::string ts_start;
    std::optional<std::int64_t> ttft_ms;
};

inline void from_json(const nlohmann::json& j, CliUsageEvent& value) {
    if (j.contains("cached_tokens") && !j.at("cached_tokens").is_null()) {
        value.cached_tokens = j.at("cached_tokens").get<std::int64_t>();
    } else {
        value.cached_tokens = std::int64_t{};
    }
    if (j.contains("completion_tokens") && !j.at("completion_tokens").is_null()) {
        value.completion_tokens = j.at("completion_tokens").get<std::int64_t>();
    } else {
        value.completion_tokens = std::int64_t{};
    }
    if (j.contains("cost_micros") && !j.at("cost_micros").is_null()) {
        value.cost_micros = j.at("cost_micros").get<std::int64_t>();
    } else {
        value.cost_micros = std::int64_t{};
    }
    if (j.contains("error_code") && !j.at("error_code").is_null()) {
        value.error_code = j.at("error_code").get<std::string>();
    } else {
        value.error_code = std::nullopt;
    }
    if (j.contains("harness") && !j.at("harness").is_null()) {
        value.harness = j.at("harness").get<Harness>();
    } else {
        value.harness = std::nullopt;
    }
    if (j.contains("model") && !j.at("model").is_null()) {
        value.model = j.at("model").get<std::string>();
    } else {
        value.model = std::string{};
    }
    if (j.contains("prompt_tokens") && !j.at("prompt_tokens").is_null()) {
        value.prompt_tokens = j.at("prompt_tokens").get<std::int64_t>();
    } else {
        value.prompt_tokens = std::int64_t{};
    }
    if (j.contains("request_id") && !j.at("request_id").is_null()) {
        value.request_id = j.at("request_id").get<std::string>();
    } else {
        value.request_id = std::string{};
    }
    if (j.contains("status_code") && !j.at("status_code").is_null()) {
        value.status_code = j.at("status_code").get<std::int64_t>();
    } else {
        value.status_code = std::int64_t{};
    }
    if (j.contains("ts_start") && !j.at("ts_start").is_null()) {
        value.ts_start = j.at("ts_start").get<std::string>();
    } else {
        value.ts_start = std::string{};
    }
    if (j.contains("ttft_ms") && !j.at("ttft_ms").is_null()) {
        value.ttft_ms = j.at("ttft_ms").get<std::int64_t>();
    } else {
        value.ttft_ms = std::nullopt;
    }
}

inline void to_json(nlohmann::json& j, const CliUsageEvent& value) {
    j = nlohmann::json::object();
    j["cached_tokens"] = value.cached_tokens;
    j["completion_tokens"] = value.completion_tokens;
    j["cost_micros"] = value.cost_micros;
    if (value.error_code.has_value()) {
        j["error_code"] = *value.error_code;
    }
    if (value.harness.has_value()) {
        j["harness"] = *value.harness;
    }
    j["model"] = value.model;
    j["prompt_tokens"] = value.prompt_tokens;
    j["request_id"] = value.request_id;
    j["status_code"] = value.status_code;
    j["ts_start"] = value.ts_start;
    if (value.ttft_ms.has_value()) {
        j["ttft_ms"] = *value.ttft_ms;
    }
}

struct CreditResponse {
    std::int64_t balance_micros;
    std::int64_t granted_micros;
    std::int64_t spent_micros;
};

inline void from_json(const nlohmann::json& j, CreditResponse& value) {
    if (j.contains("balance_micros") && !j.at("balance_micros").is_null()) {
        value.balance_micros = j.at("balance_micros").get<std::int64_t>();
    } else {
        value.balance_micros = std::int64_t{};
    }
    if (j.contains("granted_micros") && !j.at("granted_micros").is_null()) {
        value.granted_micros = j.at("granted_micros").get<std::int64_t>();
    } else {
        value.granted_micros = std::int64_t{};
    }
    if (j.contains("spent_micros") && !j.at("spent_micros").is_null()) {
        value.spent_micros = j.at("spent_micros").get<std::int64_t>();
    } else {
        value.spent_micros = std::int64_t{};
    }
}

inline void to_json(nlohmann::json& j, const CreditResponse& value) {
    j = nlohmann::json::object();
    j["balance_micros"] = value.balance_micros;
    j["granted_micros"] = value.granted_micros;
    j["spent_micros"] = value.spent_micros;
}

struct UsageModelRollup {
    std::int64_t cached_tokens;
    std::int64_t completion_tokens;
    std::int64_t cost_micros;
    std::string model;
    std::int64_t prompt_tokens;
    std::int64_t requests;
};

inline void from_json(const nlohmann::json& j, UsageModelRollup& value) {
    if (j.contains("cached_tokens") && !j.at("cached_tokens").is_null()) {
        value.cached_tokens = j.at("cached_tokens").get<std::int64_t>();
    } else {
        value.cached_tokens = std::int64_t{};
    }
    if (j.contains("completion_tokens") && !j.at("completion_tokens").is_null()) {
        value.completion_tokens = j.at("completion_tokens").get<std::int64_t>();
    } else {
        value.completion_tokens = std::int64_t{};
    }
    if (j.contains("cost_micros") && !j.at("cost_micros").is_null()) {
        value.cost_micros = j.at("cost_micros").get<std::int64_t>();
    } else {
        value.cost_micros = std::int64_t{};
    }
    if (j.contains("model") && !j.at("model").is_null()) {
        value.model = j.at("model").get<std::string>();
    } else {
        value.model = std::string{};
    }
    if (j.contains("prompt_tokens") && !j.at("prompt_tokens").is_null()) {
        value.prompt_tokens = j.at("prompt_tokens").get<std::int64_t>();
    } else {
        value.prompt_tokens = std::int64_t{};
    }
    if (j.contains("requests") && !j.at("requests").is_null()) {
        value.requests = j.at("requests").get<std::int64_t>();
    } else {
        value.requests = std::int64_t{};
    }
}

inline void to_json(nlohmann::json& j, const UsageModelRollup& value) {
    j = nlohmann::json::object();
    j["cached_tokens"] = value.cached_tokens;
    j["completion_tokens"] = value.completion_tokens;
    j["cost_micros"] = value.cost_micros;
    j["model"] = value.model;
    j["prompt_tokens"] = value.prompt_tokens;
    j["requests"] = value.requests;
}

struct UsageTimelinePoint {
    std::int64_t completion_tokens;
    std::int64_t cost_micros;
    std::string date;
    std::int64_t prompt_tokens;
    std::int64_t requests;
};

inline void from_json(const nlohmann::json& j, UsageTimelinePoint& value) {
    if (j.contains("completion_tokens") && !j.at("completion_tokens").is_null()) {
        value.completion_tokens = j.at("completion_tokens").get<std::int64_t>();
    } else {
        value.completion_tokens = std::int64_t{};
    }
    if (j.contains("cost_micros") && !j.at("cost_micros").is_null()) {
        value.cost_micros = j.at("cost_micros").get<std::int64_t>();
    } else {
        value.cost_micros = std::int64_t{};
    }
    if (j.contains("date") && !j.at("date").is_null()) {
        value.date = j.at("date").get<std::string>();
    } else {
        value.date = std::string{};
    }
    if (j.contains("prompt_tokens") && !j.at("prompt_tokens").is_null()) {
        value.prompt_tokens = j.at("prompt_tokens").get<std::int64_t>();
    } else {
        value.prompt_tokens = std::int64_t{};
    }
    if (j.contains("requests") && !j.at("requests").is_null()) {
        value.requests = j.at("requests").get<std::int64_t>();
    } else {
        value.requests = std::int64_t{};
    }
}

inline void to_json(nlohmann::json& j, const UsageTimelinePoint& value) {
    j = nlohmann::json::object();
    j["completion_tokens"] = value.completion_tokens;
    j["cost_micros"] = value.cost_micros;
    j["date"] = value.date;
    j["prompt_tokens"] = value.prompt_tokens;
    j["requests"] = value.requests;
}

struct UsageTotals {
    std::int64_t cached_tokens;
    std::int64_t completion_tokens;
    std::int64_t cost_micros;
    std::int64_t prompt_tokens;
    std::int64_t requests;
};

inline void from_json(const nlohmann::json& j, UsageTotals& value) {
    if (j.contains("cached_tokens") && !j.at("cached_tokens").is_null()) {
        value.cached_tokens = j.at("cached_tokens").get<std::int64_t>();
    } else {
        value.cached_tokens = std::int64_t{};
    }
    if (j.contains("completion_tokens") && !j.at("completion_tokens").is_null()) {
        value.completion_tokens = j.at("completion_tokens").get<std::int64_t>();
    } else {
        value.completion_tokens = std::int64_t{};
    }
    if (j.contains("cost_micros") && !j.at("cost_micros").is_null()) {
        value.cost_micros = j.at("cost_micros").get<std::int64_t>();
    } else {
        value.cost_micros = std::int64_t{};
    }
    if (j.contains("prompt_tokens") && !j.at("prompt_tokens").is_null()) {
        value.prompt_tokens = j.at("prompt_tokens").get<std::int64_t>();
    } else {
        value.prompt_tokens = std::int64_t{};
    }
    if (j.contains("requests") && !j.at("requests").is_null()) {
        value.requests = j.at("requests").get<std::int64_t>();
    } else {
        value.requests = std::int64_t{};
    }
}

inline void to_json(nlohmann::json& j, const UsageTotals& value) {
    j = nlohmann::json::object();
    j["cached_tokens"] = value.cached_tokens;
    j["completion_tokens"] = value.completion_tokens;
    j["cost_micros"] = value.cost_micros;
    j["prompt_tokens"] = value.prompt_tokens;
    j["requests"] = value.requests;
}

struct CliUsageWindow {
    std::int64_t seconds;
    UsageTotals totals;
    CliUsageWindowLabel window;
};

inline void from_json(const nlohmann::json& j, CliUsageWindow& value) {
    if (j.contains("seconds") && !j.at("seconds").is_null()) {
        value.seconds = j.at("seconds").get<std::int64_t>();
    } else {
        value.seconds = std::int64_t{};
    }
    if (j.contains("totals") && !j.at("totals").is_null()) {
        value.totals = j.at("totals").get<UsageTotals>();
    } else {
        value.totals = UsageTotals{};
    }
    if (j.contains("window") && !j.at("window").is_null()) {
        value.window = j.at("window").get<CliUsageWindowLabel>();
    } else {
        value.window = CliUsageWindowLabel{};
    }
}

inline void to_json(nlohmann::json& j, const CliUsageWindow& value) {
    j = nlohmann::json::object();
    j["seconds"] = value.seconds;
    j["totals"] = value.totals;
    j["window"] = value.window;
}

struct CliUsageResponse {
    CreditResponse credit;
    std::vector<UsageModelRollup> models;
    std::vector<CliUsageEvent> recent;
    std::vector<UsageTimelinePoint> timeline;
    UsageTotals totals;
    std::vector<CliUsageWindow> windows;
};

inline void from_json(const nlohmann::json& j, CliUsageResponse& value) {
    if (j.contains("credit") && !j.at("credit").is_null()) {
        value.credit = j.at("credit").get<CreditResponse>();
    } else {
        value.credit = CreditResponse{};
    }
    if (j.contains("models") && !j.at("models").is_null()) {
        value.models = j.at("models").get<std::vector<UsageModelRollup>>();
    } else {
        value.models = std::vector<UsageModelRollup>{};
    }
    if (j.contains("recent") && !j.at("recent").is_null()) {
        value.recent = j.at("recent").get<std::vector<CliUsageEvent>>();
    } else {
        value.recent = std::vector<CliUsageEvent>{};
    }
    if (j.contains("timeline") && !j.at("timeline").is_null()) {
        value.timeline = j.at("timeline").get<std::vector<UsageTimelinePoint>>();
    } else {
        value.timeline = std::vector<UsageTimelinePoint>{};
    }
    if (j.contains("totals") && !j.at("totals").is_null()) {
        value.totals = j.at("totals").get<UsageTotals>();
    } else {
        value.totals = UsageTotals{};
    }
    if (j.contains("windows") && !j.at("windows").is_null()) {
        value.windows = j.at("windows").get<std::vector<CliUsageWindow>>();
    } else {
        value.windows = std::vector<CliUsageWindow>{};
    }
}

inline void to_json(nlohmann::json& j, const CliUsageResponse& value) {
    j = nlohmann::json::object();
    j["credit"] = value.credit;
    j["models"] = value.models;
    j["recent"] = value.recent;
    j["timeline"] = value.timeline;
    j["totals"] = value.totals;
    j["windows"] = value.windows;
}

struct GrantResponse {
    std::string access_token;
    std::string email;
    std::int64_t expires_in;
    CliPlan plan;
    std::string refresh_token;
};

inline void from_json(const nlohmann::json& j, GrantResponse& value) {
    if (j.contains("access_token") && !j.at("access_token").is_null()) {
        value.access_token = j.at("access_token").get<std::string>();
    } else {
        value.access_token = std::string{};
    }
    if (j.contains("email") && !j.at("email").is_null()) {
        value.email = j.at("email").get<std::string>();
    } else {
        value.email = std::string{};
    }
    if (j.contains("expires_in") && !j.at("expires_in").is_null()) {
        value.expires_in = j.at("expires_in").get<std::int64_t>();
    } else {
        value.expires_in = std::int64_t{};
    }
    if (j.contains("plan") && !j.at("plan").is_null()) {
        value.plan = j.at("plan").get<CliPlan>();
    } else {
        value.plan = CliPlan{};
    }
    if (j.contains("refresh_token") && !j.at("refresh_token").is_null()) {
        value.refresh_token = j.at("refresh_token").get<std::string>();
    } else {
        value.refresh_token = std::string{};
    }
}

inline void to_json(nlohmann::json& j, const GrantResponse& value) {
    j = nlohmann::json::object();
    j["access_token"] = value.access_token;
    j["email"] = value.email;
    j["expires_in"] = value.expires_in;
    j["plan"] = value.plan;
    j["refresh_token"] = value.refresh_token;
}

struct IdentityResponse {
    std::string email;
    std::int64_t monthly_token_limit;
    CliPlan plan;
    std::int64_t tokens_this_month;
};

inline void from_json(const nlohmann::json& j, IdentityResponse& value) {
    if (j.contains("email") && !j.at("email").is_null()) {
        value.email = j.at("email").get<std::string>();
    } else {
        value.email = std::string{};
    }
    if (j.contains("monthly_token_limit") && !j.at("monthly_token_limit").is_null()) {
        value.monthly_token_limit = j.at("monthly_token_limit").get<std::int64_t>();
    } else {
        value.monthly_token_limit = std::int64_t{};
    }
    if (j.contains("plan") && !j.at("plan").is_null()) {
        value.plan = j.at("plan").get<CliPlan>();
    } else {
        value.plan = CliPlan{};
    }
    if (j.contains("tokens_this_month") && !j.at("tokens_this_month").is_null()) {
        value.tokens_this_month = j.at("tokens_this_month").get<std::int64_t>();
    } else {
        value.tokens_this_month = std::int64_t{};
    }
}

inline void to_json(nlohmann::json& j, const IdentityResponse& value) {
    j = nlohmann::json::object();
    j["email"] = value.email;
    j["monthly_token_limit"] = value.monthly_token_limit;
    j["plan"] = value.plan;
    j["tokens_this_month"] = value.tokens_this_month;
}

struct ModelCatalogResponse {
    std::string effective_from;
    std::vector<CatalogModelResponse> models;
    std::string pricing_version;
};

inline void from_json(const nlohmann::json& j, ModelCatalogResponse& value) {
    if (j.contains("effective_from") && !j.at("effective_from").is_null()) {
        value.effective_from = j.at("effective_from").get<std::string>();
    } else {
        value.effective_from = std::string{};
    }
    if (j.contains("models") && !j.at("models").is_null()) {
        value.models = j.at("models").get<std::vector<CatalogModelResponse>>();
    } else {
        value.models = std::vector<CatalogModelResponse>{};
    }
    if (j.contains("pricing_version") && !j.at("pricing_version").is_null()) {
        value.pricing_version = j.at("pricing_version").get<std::string>();
    } else {
        value.pricing_version = std::string{};
    }
}

inline void to_json(nlohmann::json& j, const ModelCatalogResponse& value) {
    j = nlohmann::json::object();
    j["effective_from"] = value.effective_from;
    j["models"] = value.models;
    j["pricing_version"] = value.pricing_version;
}

struct PublicModel {
    std::optional<std::int64_t> created;
    std::string id;
    std::optional<std::int64_t> max_input_tokens;
    std::optional<std::int64_t> max_output_tokens;
    std::optional<std::string> mode;
    std::string object;
    std::string owned_by;
};

inline void from_json(const nlohmann::json& j, PublicModel& value) {
    if (j.contains("created") && !j.at("created").is_null()) {
        value.created = j.at("created").get<std::int64_t>();
    } else {
        value.created = std::nullopt;
    }
    if (j.contains("id") && !j.at("id").is_null()) {
        value.id = j.at("id").get<std::string>();
    } else {
        value.id = std::string{};
    }
    if (j.contains("max_input_tokens") && !j.at("max_input_tokens").is_null()) {
        value.max_input_tokens = j.at("max_input_tokens").get<std::int64_t>();
    } else {
        value.max_input_tokens = std::nullopt;
    }
    if (j.contains("max_output_tokens") && !j.at("max_output_tokens").is_null()) {
        value.max_output_tokens = j.at("max_output_tokens").get<std::int64_t>();
    } else {
        value.max_output_tokens = std::nullopt;
    }
    if (j.contains("mode") && !j.at("mode").is_null()) {
        value.mode = j.at("mode").get<std::string>();
    } else {
        value.mode = std::nullopt;
    }
    if (j.contains("object") && !j.at("object").is_null()) {
        value.object = j.at("object").get<std::string>();
    } else {
        value.object = std::string{};
    }
    if (j.contains("owned_by") && !j.at("owned_by").is_null()) {
        value.owned_by = j.at("owned_by").get<std::string>();
    } else {
        value.owned_by = std::string{};
    }
}

inline void to_json(nlohmann::json& j, const PublicModel& value) {
    j = nlohmann::json::object();
    if (value.created.has_value()) {
        j["created"] = *value.created;
    }
    j["id"] = value.id;
    if (value.max_input_tokens.has_value()) {
        j["max_input_tokens"] = *value.max_input_tokens;
    }
    if (value.max_output_tokens.has_value()) {
        j["max_output_tokens"] = *value.max_output_tokens;
    }
    if (value.mode.has_value()) {
        j["mode"] = *value.mode;
    }
    j["object"] = value.object;
    j["owned_by"] = value.owned_by;
}

struct ModelList {
    std::vector<PublicModel> data;
    std::string object;
};

inline void from_json(const nlohmann::json& j, ModelList& value) {
    if (j.contains("data") && !j.at("data").is_null()) {
        value.data = j.at("data").get<std::vector<PublicModel>>();
    } else {
        value.data = std::vector<PublicModel>{};
    }
    if (j.contains("object") && !j.at("object").is_null()) {
        value.object = j.at("object").get<std::string>();
    } else {
        value.object = std::string{};
    }
}

inline void to_json(nlohmann::json& j, const ModelList& value) {
    j = nlohmann::json::object();
    j["data"] = value.data;
    j["object"] = value.object;
}

struct OpenAIErrorDetail {
    std::optional<ErrorCode> code;
    std::string message;
    std::optional<std::string> param;
    ErrorType type;
};

inline void from_json(const nlohmann::json& j, OpenAIErrorDetail& value) {
    if (j.contains("code") && !j.at("code").is_null()) {
        value.code = j.at("code").get<ErrorCode>();
    } else {
        value.code = std::nullopt;
    }
    if (j.contains("message") && !j.at("message").is_null()) {
        value.message = j.at("message").get<std::string>();
    } else {
        value.message = std::string{};
    }
    if (j.contains("param") && !j.at("param").is_null()) {
        value.param = j.at("param").get<std::string>();
    } else {
        value.param = std::nullopt;
    }
    if (j.contains("type") && !j.at("type").is_null()) {
        value.type = j.at("type").get<ErrorType>();
    } else {
        value.type = ErrorType{};
    }
}

inline void to_json(nlohmann::json& j, const OpenAIErrorDetail& value) {
    j = nlohmann::json::object();
    if (value.code.has_value()) {
        j["code"] = *value.code;
    }
    j["message"] = value.message;
    if (value.param.has_value()) {
        j["param"] = *value.param;
    }
    j["type"] = value.type;
}

struct OpenAIError {
    OpenAIErrorDetail error;
};

inline void from_json(const nlohmann::json& j, OpenAIError& value) {
    if (j.contains("error") && !j.at("error").is_null()) {
        value.error = j.at("error").get<OpenAIErrorDetail>();
    } else {
        value.error = OpenAIErrorDetail{};
    }
}

inline void to_json(nlohmann::json& j, const OpenAIError& value) {
    j = nlohmann::json::object();
    j["error"] = value.error;
}

struct PollResponse {
    std::optional<std::string> access_token;
    std::optional<std::string> email;
    std::optional<std::int64_t> expires_in;
    std::optional<CliPlan> plan;
    std::optional<std::string> refresh_token;
    PollStatus status;
};

inline void from_json(const nlohmann::json& j, PollResponse& value) {
    if (j.contains("access_token") && !j.at("access_token").is_null()) {
        value.access_token = j.at("access_token").get<std::string>();
    } else {
        value.access_token = std::nullopt;
    }
    if (j.contains("email") && !j.at("email").is_null()) {
        value.email = j.at("email").get<std::string>();
    } else {
        value.email = std::nullopt;
    }
    if (j.contains("expires_in") && !j.at("expires_in").is_null()) {
        value.expires_in = j.at("expires_in").get<std::int64_t>();
    } else {
        value.expires_in = std::nullopt;
    }
    if (j.contains("plan") && !j.at("plan").is_null()) {
        value.plan = j.at("plan").get<CliPlan>();
    } else {
        value.plan = std::nullopt;
    }
    if (j.contains("refresh_token") && !j.at("refresh_token").is_null()) {
        value.refresh_token = j.at("refresh_token").get<std::string>();
    } else {
        value.refresh_token = std::nullopt;
    }
    if (j.contains("status") && !j.at("status").is_null()) {
        value.status = j.at("status").get<PollStatus>();
    } else {
        value.status = PollStatus{};
    }
}

inline void to_json(nlohmann::json& j, const PollResponse& value) {
    j = nlohmann::json::object();
    if (value.access_token.has_value()) {
        j["access_token"] = *value.access_token;
    }
    if (value.email.has_value()) {
        j["email"] = *value.email;
    }
    if (value.expires_in.has_value()) {
        j["expires_in"] = *value.expires_in;
    }
    if (value.plan.has_value()) {
        j["plan"] = *value.plan;
    }
    if (value.refresh_token.has_value()) {
        j["refresh_token"] = *value.refresh_token;
    }
    j["status"] = value.status;
}

}  // namespace wally::account::contract

#endif  // WALLY_ACCOUNT_CONSOLE_CONTRACT_H
