// Generated by contracts/generate_console_binding.py from
// contracts/wally-cli-v1.openapi.json. DO NOT EDIT.
//
// Typed request and response models for the CLI's control-plane calls, so
// console.rs neither builds a request body by hand nor reads a response
// field by name. Regenerate and commit whenever the pinned contract moves.
#![allow(clippy::all)]

use serde_json::Value;

/// SHA-256 of contracts/wally-cli-v1.openapi.json this file was built from.
pub const CONTRACT_SHA256: &str =
    "cd8b65933cdd82a72e1679947880359c5732f025e45f88948602b6b9c39e2adc";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ApiErrorCode {
    #[default]
    KInvalidRequest,
    KUnauthorized,
    KForbidden,
    KNotFound,
    KMethodNotAllowed,
    KConflict,
    KGone,
    KPayloadTooLarge,
    KRateLimited,
    KInternalError,
    KUpstreamUnavailable,
    KServiceUnavailable,
    KTimeout,
    KBadRequest,
    KControlPlaneOverloaded,
    KDefaultKeyUnavailable,
    KExpiredApiKey,
    KGatewayUnavailable,
    KIdempotencyKeyReused,
    KInsufficientCredit,
    KInvalidApiKey,
    KModelNotEntitled,
    KNotInCohort,
    KProvisioningUnavailable,
    KProxyRetired,
    KRevokedApiKey,
    KSignupMethodNotAllowed,
    KUpstreamContractViolation,
    KUserRateLimited,
    KGatewayNotConfigured,
    KGatewayTimeout,
    KGatewayProtocolError,
    KGatewayOperationPending,
    KReconciliationUnverified,
    KRetentionManagedByRunanywhere,
    KCardRequired,
}

impl ApiErrorCode {
    pub fn as_str(&self) -> &'static str {
        match self {
            ApiErrorCode::KInvalidRequest => "invalid_request",
            ApiErrorCode::KUnauthorized => "unauthorized",
            ApiErrorCode::KForbidden => "forbidden",
            ApiErrorCode::KNotFound => "not_found",
            ApiErrorCode::KMethodNotAllowed => "method_not_allowed",
            ApiErrorCode::KConflict => "conflict",
            ApiErrorCode::KGone => "gone",
            ApiErrorCode::KPayloadTooLarge => "payload_too_large",
            ApiErrorCode::KRateLimited => "rate_limited",
            ApiErrorCode::KInternalError => "internal_error",
            ApiErrorCode::KUpstreamUnavailable => "upstream_unavailable",
            ApiErrorCode::KServiceUnavailable => "service_unavailable",
            ApiErrorCode::KTimeout => "timeout",
            ApiErrorCode::KBadRequest => "bad_request",
            ApiErrorCode::KControlPlaneOverloaded => "control_plane_overloaded",
            ApiErrorCode::KDefaultKeyUnavailable => "default_key_unavailable",
            ApiErrorCode::KExpiredApiKey => "expired_api_key",
            ApiErrorCode::KGatewayUnavailable => "gateway_unavailable",
            ApiErrorCode::KIdempotencyKeyReused => "idempotency_key_reused",
            ApiErrorCode::KInsufficientCredit => "insufficient_credit",
            ApiErrorCode::KInvalidApiKey => "invalid_api_key",
            ApiErrorCode::KModelNotEntitled => "model_not_entitled",
            ApiErrorCode::KNotInCohort => "not_in_cohort",
            ApiErrorCode::KProvisioningUnavailable => "provisioning_unavailable",
            ApiErrorCode::KProxyRetired => "proxy_retired",
            ApiErrorCode::KRevokedApiKey => "revoked_api_key",
            ApiErrorCode::KSignupMethodNotAllowed => "signup_method_not_allowed",
            ApiErrorCode::KUpstreamContractViolation => "upstream_contract_violation",
            ApiErrorCode::KUserRateLimited => "user_rate_limited",
            ApiErrorCode::KGatewayNotConfigured => "gateway_not_configured",
            ApiErrorCode::KGatewayTimeout => "gateway_timeout",
            ApiErrorCode::KGatewayProtocolError => "gateway_protocol_error",
            ApiErrorCode::KGatewayOperationPending => "gateway_operation_pending",
            ApiErrorCode::KReconciliationUnverified => "reconciliation_unverified",
            ApiErrorCode::KRetentionManagedByRunanywhere => "retention_managed_by_runanywhere",
            ApiErrorCode::KCardRequired => "card_required",
        }
    }

    pub fn parse(raw: &str) -> Result<Self, String> {
        match raw {
            "invalid_request" => Ok(ApiErrorCode::KInvalidRequest),
            "unauthorized" => Ok(ApiErrorCode::KUnauthorized),
            "forbidden" => Ok(ApiErrorCode::KForbidden),
            "not_found" => Ok(ApiErrorCode::KNotFound),
            "method_not_allowed" => Ok(ApiErrorCode::KMethodNotAllowed),
            "conflict" => Ok(ApiErrorCode::KConflict),
            "gone" => Ok(ApiErrorCode::KGone),
            "payload_too_large" => Ok(ApiErrorCode::KPayloadTooLarge),
            "rate_limited" => Ok(ApiErrorCode::KRateLimited),
            "internal_error" => Ok(ApiErrorCode::KInternalError),
            "upstream_unavailable" => Ok(ApiErrorCode::KUpstreamUnavailable),
            "service_unavailable" => Ok(ApiErrorCode::KServiceUnavailable),
            "timeout" => Ok(ApiErrorCode::KTimeout),
            "bad_request" => Ok(ApiErrorCode::KBadRequest),
            "control_plane_overloaded" => Ok(ApiErrorCode::KControlPlaneOverloaded),
            "default_key_unavailable" => Ok(ApiErrorCode::KDefaultKeyUnavailable),
            "expired_api_key" => Ok(ApiErrorCode::KExpiredApiKey),
            "gateway_unavailable" => Ok(ApiErrorCode::KGatewayUnavailable),
            "idempotency_key_reused" => Ok(ApiErrorCode::KIdempotencyKeyReused),
            "insufficient_credit" => Ok(ApiErrorCode::KInsufficientCredit),
            "invalid_api_key" => Ok(ApiErrorCode::KInvalidApiKey),
            "model_not_entitled" => Ok(ApiErrorCode::KModelNotEntitled),
            "not_in_cohort" => Ok(ApiErrorCode::KNotInCohort),
            "provisioning_unavailable" => Ok(ApiErrorCode::KProvisioningUnavailable),
            "proxy_retired" => Ok(ApiErrorCode::KProxyRetired),
            "revoked_api_key" => Ok(ApiErrorCode::KRevokedApiKey),
            "signup_method_not_allowed" => Ok(ApiErrorCode::KSignupMethodNotAllowed),
            "upstream_contract_violation" => Ok(ApiErrorCode::KUpstreamContractViolation),
            "user_rate_limited" => Ok(ApiErrorCode::KUserRateLimited),
            "gateway_not_configured" => Ok(ApiErrorCode::KGatewayNotConfigured),
            "gateway_timeout" => Ok(ApiErrorCode::KGatewayTimeout),
            "gateway_protocol_error" => Ok(ApiErrorCode::KGatewayProtocolError),
            "gateway_operation_pending" => Ok(ApiErrorCode::KGatewayOperationPending),
            "reconciliation_unverified" => Ok(ApiErrorCode::KReconciliationUnverified),
            "retention_managed_by_runanywhere" => Ok(ApiErrorCode::KRetentionManagedByRunanywhere),
            "card_required" => Ok(ApiErrorCode::KCardRequired),
            other => Err(format!("unknown ApiErrorCode: {other}")),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum CliClient {
    #[default]
    KRcli,
}

impl CliClient {
    pub fn as_str(&self) -> &'static str {
        match self {
            CliClient::KRcli => "rcli",
        }
    }

    pub fn parse(raw: &str) -> Result<Self, String> {
        match raw {
            "rcli" => Ok(CliClient::KRcli),
            other => Err(format!("unknown CliClient: {other}")),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum CliPlan {
    #[default]
    KBeta,
}

impl CliPlan {
    pub fn as_str(&self) -> &'static str {
        match self {
            CliPlan::KBeta => "beta",
        }
    }

    pub fn parse(raw: &str) -> Result<Self, String> {
        match raw {
            "beta" => Ok(CliPlan::KBeta),
            other => Err(format!("unknown CliPlan: {other}")),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum CliUsageWindowLabel {
    #[default]
    K1h,
    K24h,
}

impl CliUsageWindowLabel {
    pub fn as_str(&self) -> &'static str {
        match self {
            CliUsageWindowLabel::K1h => "1h",
            CliUsageWindowLabel::K24h => "24h",
        }
    }

    pub fn parse(raw: &str) -> Result<Self, String> {
        match raw {
            "1h" => Ok(CliUsageWindowLabel::K1h),
            "24h" => Ok(CliUsageWindowLabel::K24h),
            other => Err(format!("unknown CliUsageWindowLabel: {other}")),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ErrorCode {
    #[default]
    KBadRequest,
    KNotFound,
    KPayloadTooLarge,
    KUnprocessable,
    KInvalidApiKey,
    KExpiredApiKey,
    KRevokedApiKey,
    KInsufficientCredit,
    KAccountFrozen,
    KModelNotEntitled,
    KNotInCohort,
    KUserRateLimited,
    KRequestCancelled,
    KQuotaExceeded,
    KCapacityExceeded,
    KIdempotencyKeyReused,
    KUnsupportedEndpoint,
    KProxyRetired,
    KGatewayUnavailable,
    KControlPlaneOverloaded,
    KCreditGateUnavailable,
    KUpstreamContractViolation,
    KUnattributedKey,
    KInternal,
    KBadGateway,
    KDraining,
    KSpoolUnhealthy,
    KCold,
    KTimeout,
}

impl ErrorCode {
    pub fn as_str(&self) -> &'static str {
        match self {
            ErrorCode::KBadRequest => "bad_request",
            ErrorCode::KNotFound => "not_found",
            ErrorCode::KPayloadTooLarge => "payload_too_large",
            ErrorCode::KUnprocessable => "unprocessable",
            ErrorCode::KInvalidApiKey => "invalid_api_key",
            ErrorCode::KExpiredApiKey => "expired_api_key",
            ErrorCode::KRevokedApiKey => "revoked_api_key",
            ErrorCode::KInsufficientCredit => "insufficient_credit",
            ErrorCode::KAccountFrozen => "account_frozen",
            ErrorCode::KModelNotEntitled => "model_not_entitled",
            ErrorCode::KNotInCohort => "not_in_cohort",
            ErrorCode::KUserRateLimited => "user_rate_limited",
            ErrorCode::KRequestCancelled => "request_cancelled",
            ErrorCode::KQuotaExceeded => "quota_exceeded",
            ErrorCode::KCapacityExceeded => "capacity_exceeded",
            ErrorCode::KIdempotencyKeyReused => "idempotency_key_reused",
            ErrorCode::KUnsupportedEndpoint => "unsupported_endpoint",
            ErrorCode::KProxyRetired => "proxy_retired",
            ErrorCode::KGatewayUnavailable => "gateway_unavailable",
            ErrorCode::KControlPlaneOverloaded => "control_plane_overloaded",
            ErrorCode::KCreditGateUnavailable => "credit_gate_unavailable",
            ErrorCode::KUpstreamContractViolation => "upstream_contract_violation",
            ErrorCode::KUnattributedKey => "unattributed_key",
            ErrorCode::KInternal => "internal",
            ErrorCode::KBadGateway => "bad_gateway",
            ErrorCode::KDraining => "draining",
            ErrorCode::KSpoolUnhealthy => "spool_unhealthy",
            ErrorCode::KCold => "cold",
            ErrorCode::KTimeout => "timeout",
        }
    }

    pub fn parse(raw: &str) -> Result<Self, String> {
        match raw {
            "bad_request" => Ok(ErrorCode::KBadRequest),
            "not_found" => Ok(ErrorCode::KNotFound),
            "payload_too_large" => Ok(ErrorCode::KPayloadTooLarge),
            "unprocessable" => Ok(ErrorCode::KUnprocessable),
            "invalid_api_key" => Ok(ErrorCode::KInvalidApiKey),
            "expired_api_key" => Ok(ErrorCode::KExpiredApiKey),
            "revoked_api_key" => Ok(ErrorCode::KRevokedApiKey),
            "insufficient_credit" => Ok(ErrorCode::KInsufficientCredit),
            "account_frozen" => Ok(ErrorCode::KAccountFrozen),
            "model_not_entitled" => Ok(ErrorCode::KModelNotEntitled),
            "not_in_cohort" => Ok(ErrorCode::KNotInCohort),
            "user_rate_limited" => Ok(ErrorCode::KUserRateLimited),
            "request_cancelled" => Ok(ErrorCode::KRequestCancelled),
            "quota_exceeded" => Ok(ErrorCode::KQuotaExceeded),
            "capacity_exceeded" => Ok(ErrorCode::KCapacityExceeded),
            "idempotency_key_reused" => Ok(ErrorCode::KIdempotencyKeyReused),
            "unsupported_endpoint" => Ok(ErrorCode::KUnsupportedEndpoint),
            "proxy_retired" => Ok(ErrorCode::KProxyRetired),
            "gateway_unavailable" => Ok(ErrorCode::KGatewayUnavailable),
            "control_plane_overloaded" => Ok(ErrorCode::KControlPlaneOverloaded),
            "credit_gate_unavailable" => Ok(ErrorCode::KCreditGateUnavailable),
            "upstream_contract_violation" => Ok(ErrorCode::KUpstreamContractViolation),
            "unattributed_key" => Ok(ErrorCode::KUnattributedKey),
            "internal" => Ok(ErrorCode::KInternal),
            "bad_gateway" => Ok(ErrorCode::KBadGateway),
            "draining" => Ok(ErrorCode::KDraining),
            "spool_unhealthy" => Ok(ErrorCode::KSpoolUnhealthy),
            "cold" => Ok(ErrorCode::KCold),
            "timeout" => Ok(ErrorCode::KTimeout),
            other => Err(format!("unknown ErrorCode: {other}")),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ErrorType {
    #[default]
    KInvalidRequestError,
    KAuthenticationError,
    KPermissionError,
    KRateLimitError,
    KQuota,
    KCapacity,
    KServerError,
    KTimeout,
}

impl ErrorType {
    pub fn as_str(&self) -> &'static str {
        match self {
            ErrorType::KInvalidRequestError => "invalid_request_error",
            ErrorType::KAuthenticationError => "authentication_error",
            ErrorType::KPermissionError => "permission_error",
            ErrorType::KRateLimitError => "rate_limit_error",
            ErrorType::KQuota => "quota",
            ErrorType::KCapacity => "capacity",
            ErrorType::KServerError => "server_error",
            ErrorType::KTimeout => "timeout",
        }
    }

    pub fn parse(raw: &str) -> Result<Self, String> {
        match raw {
            "invalid_request_error" => Ok(ErrorType::KInvalidRequestError),
            "authentication_error" => Ok(ErrorType::KAuthenticationError),
            "permission_error" => Ok(ErrorType::KPermissionError),
            "rate_limit_error" => Ok(ErrorType::KRateLimitError),
            "quota" => Ok(ErrorType::KQuota),
            "capacity" => Ok(ErrorType::KCapacity),
            "server_error" => Ok(ErrorType::KServerError),
            "timeout" => Ok(ErrorType::KTimeout),
            other => Err(format!("unknown ErrorType: {other}")),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Harness {
    #[default]
    KClaudeCode,
    KClaudeDesktop,
    KOpencode,
    KHermes,
    KOpenclaw,
    KDeepseek,
    KConsole,
    KPlayground,
    KRcli,
    KSdk,
    KUnknown,
    KCursor,
    KContinue,
    KAider,
    KCline,
    KRoo,
    KZed,
    KOpenaiSdk,
    KLangchain,
    KLlamaindex,
    KCurl,
}

impl Harness {
    pub fn as_str(&self) -> &'static str {
        match self {
            Harness::KClaudeCode => "claude_code",
            Harness::KClaudeDesktop => "claude_desktop",
            Harness::KOpencode => "opencode",
            Harness::KHermes => "hermes",
            Harness::KOpenclaw => "openclaw",
            Harness::KDeepseek => "deepseek",
            Harness::KConsole => "console",
            Harness::KPlayground => "playground",
            Harness::KRcli => "rcli",
            Harness::KSdk => "sdk",
            Harness::KUnknown => "unknown",
            Harness::KCursor => "cursor",
            Harness::KContinue => "continue",
            Harness::KAider => "aider",
            Harness::KCline => "cline",
            Harness::KRoo => "roo",
            Harness::KZed => "zed",
            Harness::KOpenaiSdk => "openai_sdk",
            Harness::KLangchain => "langchain",
            Harness::KLlamaindex => "llamaindex",
            Harness::KCurl => "curl",
        }
    }

    pub fn parse(raw: &str) -> Result<Self, String> {
        match raw {
            "claude_code" => Ok(Harness::KClaudeCode),
            "claude_desktop" => Ok(Harness::KClaudeDesktop),
            "opencode" => Ok(Harness::KOpencode),
            "hermes" => Ok(Harness::KHermes),
            "openclaw" => Ok(Harness::KOpenclaw),
            "deepseek" => Ok(Harness::KDeepseek),
            "console" => Ok(Harness::KConsole),
            "playground" => Ok(Harness::KPlayground),
            "rcli" => Ok(Harness::KRcli),
            "sdk" => Ok(Harness::KSdk),
            "unknown" => Ok(Harness::KUnknown),
            "cursor" => Ok(Harness::KCursor),
            "continue" => Ok(Harness::KContinue),
            "aider" => Ok(Harness::KAider),
            "cline" => Ok(Harness::KCline),
            "roo" => Ok(Harness::KRoo),
            "zed" => Ok(Harness::KZed),
            "openai_sdk" => Ok(Harness::KOpenaiSdk),
            "langchain" => Ok(Harness::KLangchain),
            "llamaindex" => Ok(Harness::KLlamaindex),
            "curl" => Ok(Harness::KCurl),
            other => Err(format!("unknown Harness: {other}")),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum PollStatus {
    #[default]
    KPending,
    KApproved,
    KDenied,
    KExpired,
}

impl PollStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            PollStatus::KPending => "pending",
            PollStatus::KApproved => "approved",
            PollStatus::KDenied => "denied",
            PollStatus::KExpired => "expired",
        }
    }

    pub fn parse(raw: &str) -> Result<Self, String> {
        match raw {
            "pending" => Ok(PollStatus::KPending),
            "approved" => Ok(PollStatus::KApproved),
            "denied" => Ok(PollStatus::KDenied),
            "expired" => Ok(PollStatus::KExpired),
            other => Err(format!("unknown PollStatus: {other}")),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum UsageProvider {
    #[default]
    KSelfHostedSglang,
    KVertexAi,
    KUnknown,
}

impl UsageProvider {
    pub fn as_str(&self) -> &'static str {
        match self {
            UsageProvider::KSelfHostedSglang => "self_hosted_sglang",
            UsageProvider::KVertexAi => "vertex_ai",
            UsageProvider::KUnknown => "unknown",
        }
    }

    pub fn parse(raw: &str) -> Result<Self, String> {
        match raw {
            "self_hosted_sglang" => Ok(UsageProvider::KSelfHostedSglang),
            "vertex_ai" => Ok(UsageProvider::KVertexAi),
            "unknown" => Ok(UsageProvider::KUnknown),
            other => Err(format!("unknown UsageProvider: {other}")),
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ApiError {
    pub code: ApiErrorCode,
    pub message: String,
}

impl ApiError {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("code") {
            Some(field) if !field.is_null() => {
                result.code = ApiErrorCode::parse(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?,
                )?;
            }
            _ => {}
        }
        match object.get("message") {
            Some(field) if !field.is_null() => {
                result.message = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert(
            "code".to_string(),
            Value::String(self.code.as_str().to_string()),
        );
        map.insert("message".to_string(), Value::String(self.message.clone()));
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CancelRequestResponse {
    pub request_id: String,
    pub status: String,
}

impl CancelRequestResponse {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("request_id") {
            Some(field) if !field.is_null() => {
                result.request_id = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("status") {
            Some(field) if !field.is_null() => {
                result.status = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert(
            "request_id".to_string(),
            Value::String(self.request_id.clone()),
        );
        map.insert("status".to_string(), Value::String(self.status.clone()));
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CatalogModelResponse {
    pub cached_input_per_mtok: i64,
    pub display_name: String,
    pub id: String,
    pub input_per_mtok: i64,
    pub output_per_mtok: i64,
}

impl CatalogModelResponse {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("cached_input_per_mtok") {
            Some(field) if !field.is_null() => {
                result.cached_input_per_mtok = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("display_name") {
            Some(field) if !field.is_null() => {
                result.display_name = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("id") {
            Some(field) if !field.is_null() => {
                result.id = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("input_per_mtok") {
            Some(field) if !field.is_null() => {
                result.input_per_mtok = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("output_per_mtok") {
            Some(field) if !field.is_null() => {
                result.output_per_mtok = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert(
            "cached_input_per_mtok".to_string(),
            Value::from(self.cached_input_per_mtok),
        );
        map.insert(
            "display_name".to_string(),
            Value::String(self.display_name.clone()),
        );
        map.insert("id".to_string(), Value::String(self.id.clone()));
        map.insert(
            "input_per_mtok".to_string(),
            Value::from(self.input_per_mtok),
        );
        map.insert(
            "output_per_mtok".to_string(),
            Value::from(self.output_per_mtok),
        );
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CliPollRequest {
    pub poll_secret: String,
    pub request_code: String,
}

impl CliPollRequest {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("poll_secret") {
            Some(field) if !field.is_null() => {
                result.poll_secret = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("request_code") {
            Some(field) if !field.is_null() => {
                result.request_code = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert(
            "poll_secret".to_string(),
            Value::String(self.poll_secret.clone()),
        );
        map.insert(
            "request_code".to_string(),
            Value::String(self.request_code.clone()),
        );
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CliRefreshRequest {
    pub refresh_token: String,
}

impl CliRefreshRequest {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("refresh_token") {
            Some(field) if !field.is_null() => {
                result.refresh_token = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert(
            "refresh_token".to_string(),
            Value::String(self.refresh_token.clone()),
        );
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CliStartRequest {
    pub client: CliClient,
    pub hostname: String,
}

impl CliStartRequest {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("client") {
            Some(field) if !field.is_null() => {
                result.client = CliClient::parse(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?,
                )?;
            }
            _ => {}
        }
        match object.get("hostname") {
            Some(field) if !field.is_null() => {
                result.hostname = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert(
            "client".to_string(),
            Value::String(self.client.as_str().to_string()),
        );
        map.insert("hostname".to_string(), Value::String(self.hostname.clone()));
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CliStartResponse {
    pub expires_in: i64,
    pub interval: i64,
    pub poll_secret: String,
    pub request_code: String,
    pub verification_url: String,
}

impl CliStartResponse {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("expires_in") {
            Some(field) if !field.is_null() => {
                result.expires_in = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("interval") {
            Some(field) if !field.is_null() => {
                result.interval = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("poll_secret") {
            Some(field) if !field.is_null() => {
                result.poll_secret = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("request_code") {
            Some(field) if !field.is_null() => {
                result.request_code = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("verification_url") {
            Some(field) if !field.is_null() => {
                result.verification_url = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert("expires_in".to_string(), Value::from(self.expires_in));
        map.insert("interval".to_string(), Value::from(self.interval));
        map.insert(
            "poll_secret".to_string(),
            Value::String(self.poll_secret.clone()),
        );
        map.insert(
            "request_code".to_string(),
            Value::String(self.request_code.clone()),
        );
        map.insert(
            "verification_url".to_string(),
            Value::String(self.verification_url.clone()),
        );
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CliUsageEvent {
    pub cached_tokens: i64,
    pub completion_tokens: i64,
    pub cost_micros: i64,
    pub error_code: Option<String>,
    pub harness: Option<Harness>,
    pub model: String,
    pub prompt_tokens: i64,
    pub request_id: String,
    pub status_code: i64,
    pub ts_start: String,
    pub ttft_ms: Option<i64>,
}

impl CliUsageEvent {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("cached_tokens") {
            Some(field) if !field.is_null() => {
                result.cached_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("completion_tokens") {
            Some(field) if !field.is_null() => {
                result.completion_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("cost_micros") {
            Some(field) if !field.is_null() => {
                result.cost_micros = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("error_code") {
            Some(field) if !field.is_null() => {
                result.error_code = Some(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?
                        .to_string(),
                );
            }
            _ => {}
        }
        match object.get("harness") {
            Some(field) if !field.is_null() => {
                result.harness = Some(Harness::parse(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?,
                )?);
            }
            _ => {}
        }
        match object.get("model") {
            Some(field) if !field.is_null() => {
                result.model = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("prompt_tokens") {
            Some(field) if !field.is_null() => {
                result.prompt_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("request_id") {
            Some(field) if !field.is_null() => {
                result.request_id = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("status_code") {
            Some(field) if !field.is_null() => {
                result.status_code = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("ts_start") {
            Some(field) if !field.is_null() => {
                result.ts_start = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("ttft_ms") {
            Some(field) if !field.is_null() => {
                result.ttft_ms = Some(
                    field
                        .as_i64()
                        .ok_or_else(|| "expected an integer".to_string())?,
                );
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert("cached_tokens".to_string(), Value::from(self.cached_tokens));
        map.insert(
            "completion_tokens".to_string(),
            Value::from(self.completion_tokens),
        );
        map.insert("cost_micros".to_string(), Value::from(self.cost_micros));
        if let Some(item) = &self.error_code {
            map.insert("error_code".to_string(), Value::String(item.clone()));
        }
        if let Some(item) = &self.harness {
            map.insert(
                "harness".to_string(),
                Value::String(item.as_str().to_string()),
            );
        }
        map.insert("model".to_string(), Value::String(self.model.clone()));
        map.insert("prompt_tokens".to_string(), Value::from(self.prompt_tokens));
        map.insert(
            "request_id".to_string(),
            Value::String(self.request_id.clone()),
        );
        map.insert("status_code".to_string(), Value::from(self.status_code));
        map.insert("ts_start".to_string(), Value::String(self.ts_start.clone()));
        if let Some(item) = &self.ttft_ms {
            map.insert("ttft_ms".to_string(), Value::from(*item));
        }
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CreditResponse {
    pub balance_micros: i64,
    pub granted_micros: i64,
    pub spent_micros: i64,
}

impl CreditResponse {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("balance_micros") {
            Some(field) if !field.is_null() => {
                result.balance_micros = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("granted_micros") {
            Some(field) if !field.is_null() => {
                result.granted_micros = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("spent_micros") {
            Some(field) if !field.is_null() => {
                result.spent_micros = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert(
            "balance_micros".to_string(),
            Value::from(self.balance_micros),
        );
        map.insert(
            "granted_micros".to_string(),
            Value::from(self.granted_micros),
        );
        map.insert("spent_micros".to_string(), Value::from(self.spent_micros));
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct UsageModelRollup {
    pub cached_tokens: i64,
    pub completion_tokens: i64,
    pub cost_micros: i64,
    pub model: String,
    pub prompt_tokens: i64,
    pub requests: i64,
}

impl UsageModelRollup {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("cached_tokens") {
            Some(field) if !field.is_null() => {
                result.cached_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("completion_tokens") {
            Some(field) if !field.is_null() => {
                result.completion_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("cost_micros") {
            Some(field) if !field.is_null() => {
                result.cost_micros = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("model") {
            Some(field) if !field.is_null() => {
                result.model = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("prompt_tokens") {
            Some(field) if !field.is_null() => {
                result.prompt_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("requests") {
            Some(field) if !field.is_null() => {
                result.requests = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert("cached_tokens".to_string(), Value::from(self.cached_tokens));
        map.insert(
            "completion_tokens".to_string(),
            Value::from(self.completion_tokens),
        );
        map.insert("cost_micros".to_string(), Value::from(self.cost_micros));
        map.insert("model".to_string(), Value::String(self.model.clone()));
        map.insert("prompt_tokens".to_string(), Value::from(self.prompt_tokens));
        map.insert("requests".to_string(), Value::from(self.requests));
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct UsageTimelinePoint {
    pub completion_tokens: i64,
    pub cost_micros: i64,
    pub date: String,
    pub prompt_tokens: i64,
    pub requests: i64,
}

impl UsageTimelinePoint {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("completion_tokens") {
            Some(field) if !field.is_null() => {
                result.completion_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("cost_micros") {
            Some(field) if !field.is_null() => {
                result.cost_micros = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("date") {
            Some(field) if !field.is_null() => {
                result.date = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("prompt_tokens") {
            Some(field) if !field.is_null() => {
                result.prompt_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("requests") {
            Some(field) if !field.is_null() => {
                result.requests = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert(
            "completion_tokens".to_string(),
            Value::from(self.completion_tokens),
        );
        map.insert("cost_micros".to_string(), Value::from(self.cost_micros));
        map.insert("date".to_string(), Value::String(self.date.clone()));
        map.insert("prompt_tokens".to_string(), Value::from(self.prompt_tokens));
        map.insert("requests".to_string(), Value::from(self.requests));
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct UsageTotals {
    pub cached_tokens: i64,
    pub completion_tokens: i64,
    pub cost_micros: i64,
    pub prompt_tokens: i64,
    pub requests: i64,
}

impl UsageTotals {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("cached_tokens") {
            Some(field) if !field.is_null() => {
                result.cached_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("completion_tokens") {
            Some(field) if !field.is_null() => {
                result.completion_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("cost_micros") {
            Some(field) if !field.is_null() => {
                result.cost_micros = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("prompt_tokens") {
            Some(field) if !field.is_null() => {
                result.prompt_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("requests") {
            Some(field) if !field.is_null() => {
                result.requests = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert("cached_tokens".to_string(), Value::from(self.cached_tokens));
        map.insert(
            "completion_tokens".to_string(),
            Value::from(self.completion_tokens),
        );
        map.insert("cost_micros".to_string(), Value::from(self.cost_micros));
        map.insert("prompt_tokens".to_string(), Value::from(self.prompt_tokens));
        map.insert("requests".to_string(), Value::from(self.requests));
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CliUsageWindow {
    pub seconds: i64,
    pub totals: UsageTotals,
    pub window: CliUsageWindowLabel,
}

impl CliUsageWindow {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("seconds") {
            Some(field) if !field.is_null() => {
                result.seconds = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("totals") {
            Some(field) if !field.is_null() => {
                result.totals = UsageTotals::from_json(field)?;
            }
            _ => {}
        }
        match object.get("window") {
            Some(field) if !field.is_null() => {
                result.window = CliUsageWindowLabel::parse(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?,
                )?;
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert("seconds".to_string(), Value::from(self.seconds));
        map.insert("totals".to_string(), self.totals.to_json());
        map.insert(
            "window".to_string(),
            Value::String(self.window.as_str().to_string()),
        );
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CliUsageResponse {
    pub credit: CreditResponse,
    pub models: Vec<UsageModelRollup>,
    pub recent: Vec<CliUsageEvent>,
    pub timeline: Vec<UsageTimelinePoint>,
    pub totals: UsageTotals,
    pub windows: Vec<CliUsageWindow>,
}

impl CliUsageResponse {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("credit") {
            Some(field) if !field.is_null() => {
                result.credit = CreditResponse::from_json(field)?;
            }
            _ => {}
        }
        match object.get("models") {
            Some(field) if !field.is_null() => {
                result.models = {
                    let array = field
                        .as_array()
                        .ok_or_else(|| "expected an array".to_string())?;
                    let mut items = Vec::with_capacity(array.len());
                    for item in array {
                        items.push(UsageModelRollup::from_json(item)?);
                    }
                    items
                };
            }
            _ => {}
        }
        match object.get("recent") {
            Some(field) if !field.is_null() => {
                result.recent = {
                    let array = field
                        .as_array()
                        .ok_or_else(|| "expected an array".to_string())?;
                    let mut items = Vec::with_capacity(array.len());
                    for item in array {
                        items.push(CliUsageEvent::from_json(item)?);
                    }
                    items
                };
            }
            _ => {}
        }
        match object.get("timeline") {
            Some(field) if !field.is_null() => {
                result.timeline = {
                    let array = field
                        .as_array()
                        .ok_or_else(|| "expected an array".to_string())?;
                    let mut items = Vec::with_capacity(array.len());
                    for item in array {
                        items.push(UsageTimelinePoint::from_json(item)?);
                    }
                    items
                };
            }
            _ => {}
        }
        match object.get("totals") {
            Some(field) if !field.is_null() => {
                result.totals = UsageTotals::from_json(field)?;
            }
            _ => {}
        }
        match object.get("windows") {
            Some(field) if !field.is_null() => {
                result.windows = {
                    let array = field
                        .as_array()
                        .ok_or_else(|| "expected an array".to_string())?;
                    let mut items = Vec::with_capacity(array.len());
                    for item in array {
                        items.push(CliUsageWindow::from_json(item)?);
                    }
                    items
                };
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert("credit".to_string(), self.credit.to_json());
        map.insert(
            "models".to_string(),
            Value::Array(self.models.iter().map(|item| item.to_json()).collect()),
        );
        map.insert(
            "recent".to_string(),
            Value::Array(self.recent.iter().map(|item| item.to_json()).collect()),
        );
        map.insert(
            "timeline".to_string(),
            Value::Array(self.timeline.iter().map(|item| item.to_json()).collect()),
        );
        map.insert("totals".to_string(), self.totals.to_json());
        map.insert(
            "windows".to_string(),
            Value::Array(self.windows.iter().map(|item| item.to_json()).collect()),
        );
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct GrantResponse {
    pub access_token: String,
    pub email: String,
    pub expires_in: i64,
    pub plan: CliPlan,
    pub refresh_token: String,
}

impl GrantResponse {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("access_token") {
            Some(field) if !field.is_null() => {
                result.access_token = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("email") {
            Some(field) if !field.is_null() => {
                result.email = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("expires_in") {
            Some(field) if !field.is_null() => {
                result.expires_in = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("plan") {
            Some(field) if !field.is_null() => {
                result.plan = CliPlan::parse(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?,
                )?;
            }
            _ => {}
        }
        match object.get("refresh_token") {
            Some(field) if !field.is_null() => {
                result.refresh_token = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert(
            "access_token".to_string(),
            Value::String(self.access_token.clone()),
        );
        map.insert("email".to_string(), Value::String(self.email.clone()));
        map.insert("expires_in".to_string(), Value::from(self.expires_in));
        map.insert(
            "plan".to_string(),
            Value::String(self.plan.as_str().to_string()),
        );
        map.insert(
            "refresh_token".to_string(),
            Value::String(self.refresh_token.clone()),
        );
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct IdentityResponse {
    pub email: String,
    pub monthly_token_limit: i64,
    pub plan: CliPlan,
    pub tokens_this_month: i64,
}

impl IdentityResponse {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("email") {
            Some(field) if !field.is_null() => {
                result.email = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("monthly_token_limit") {
            Some(field) if !field.is_null() => {
                result.monthly_token_limit = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("plan") {
            Some(field) if !field.is_null() => {
                result.plan = CliPlan::parse(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?,
                )?;
            }
            _ => {}
        }
        match object.get("tokens_this_month") {
            Some(field) if !field.is_null() => {
                result.tokens_this_month = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert("email".to_string(), Value::String(self.email.clone()));
        map.insert(
            "monthly_token_limit".to_string(),
            Value::from(self.monthly_token_limit),
        );
        map.insert(
            "plan".to_string(),
            Value::String(self.plan.as_str().to_string()),
        );
        map.insert(
            "tokens_this_month".to_string(),
            Value::from(self.tokens_this_month),
        );
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ModelCatalogResponse {
    pub effective_from: String,
    pub models: Vec<CatalogModelResponse>,
    pub pricing_version: String,
}

impl ModelCatalogResponse {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("effective_from") {
            Some(field) if !field.is_null() => {
                result.effective_from = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("models") {
            Some(field) if !field.is_null() => {
                result.models = {
                    let array = field
                        .as_array()
                        .ok_or_else(|| "expected an array".to_string())?;
                    let mut items = Vec::with_capacity(array.len());
                    for item in array {
                        items.push(CatalogModelResponse::from_json(item)?);
                    }
                    items
                };
            }
            _ => {}
        }
        match object.get("pricing_version") {
            Some(field) if !field.is_null() => {
                result.pricing_version = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert(
            "effective_from".to_string(),
            Value::String(self.effective_from.clone()),
        );
        map.insert(
            "models".to_string(),
            Value::Array(self.models.iter().map(|item| item.to_json()).collect()),
        );
        map.insert(
            "pricing_version".to_string(),
            Value::String(self.pricing_version.clone()),
        );
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PublicModel {
    pub created: Option<i64>,
    pub id: String,
    pub max_input_tokens: Option<i64>,
    pub max_output_tokens: Option<i64>,
    pub mode: Option<String>,
    pub object: String,
    pub owned_by: String,
}

impl PublicModel {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("created") {
            Some(field) if !field.is_null() => {
                result.created = Some(
                    field
                        .as_i64()
                        .ok_or_else(|| "expected an integer".to_string())?,
                );
            }
            _ => {}
        }
        match object.get("id") {
            Some(field) if !field.is_null() => {
                result.id = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("max_input_tokens") {
            Some(field) if !field.is_null() => {
                result.max_input_tokens = Some(
                    field
                        .as_i64()
                        .ok_or_else(|| "expected an integer".to_string())?,
                );
            }
            _ => {}
        }
        match object.get("max_output_tokens") {
            Some(field) if !field.is_null() => {
                result.max_output_tokens = Some(
                    field
                        .as_i64()
                        .ok_or_else(|| "expected an integer".to_string())?,
                );
            }
            _ => {}
        }
        match object.get("mode") {
            Some(field) if !field.is_null() => {
                result.mode = Some(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?
                        .to_string(),
                );
            }
            _ => {}
        }
        match object.get("object") {
            Some(field) if !field.is_null() => {
                result.object = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("owned_by") {
            Some(field) if !field.is_null() => {
                result.owned_by = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        if let Some(item) = &self.created {
            map.insert("created".to_string(), Value::from(*item));
        }
        map.insert("id".to_string(), Value::String(self.id.clone()));
        if let Some(item) = &self.max_input_tokens {
            map.insert("max_input_tokens".to_string(), Value::from(*item));
        }
        if let Some(item) = &self.max_output_tokens {
            map.insert("max_output_tokens".to_string(), Value::from(*item));
        }
        if let Some(item) = &self.mode {
            map.insert("mode".to_string(), Value::String(item.clone()));
        }
        map.insert("object".to_string(), Value::String(self.object.clone()));
        map.insert("owned_by".to_string(), Value::String(self.owned_by.clone()));
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ModelList {
    pub data: Vec<PublicModel>,
    pub object: String,
}

impl ModelList {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("data") {
            Some(field) if !field.is_null() => {
                result.data = {
                    let array = field
                        .as_array()
                        .ok_or_else(|| "expected an array".to_string())?;
                    let mut items = Vec::with_capacity(array.len());
                    for item in array {
                        items.push(PublicModel::from_json(item)?);
                    }
                    items
                };
            }
            _ => {}
        }
        match object.get("object") {
            Some(field) if !field.is_null() => {
                result.object = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert(
            "data".to_string(),
            Value::Array(self.data.iter().map(|item| item.to_json()).collect()),
        );
        map.insert("object".to_string(), Value::String(self.object.clone()));
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct OpenAIErrorDetail {
    pub code: Option<ErrorCode>,
    pub message: String,
    pub param: Option<String>,
    pub r#type: ErrorType,
}

impl OpenAIErrorDetail {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("code") {
            Some(field) if !field.is_null() => {
                result.code = Some(ErrorCode::parse(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?,
                )?);
            }
            _ => {}
        }
        match object.get("message") {
            Some(field) if !field.is_null() => {
                result.message = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("param") {
            Some(field) if !field.is_null() => {
                result.param = Some(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?
                        .to_string(),
                );
            }
            _ => {}
        }
        match object.get("type") {
            Some(field) if !field.is_null() => {
                result.r#type = ErrorType::parse(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?,
                )?;
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        if let Some(item) = &self.code {
            map.insert("code".to_string(), Value::String(item.as_str().to_string()));
        }
        map.insert("message".to_string(), Value::String(self.message.clone()));
        if let Some(item) = &self.param {
            map.insert("param".to_string(), Value::String(item.clone()));
        }
        map.insert(
            "type".to_string(),
            Value::String(self.r#type.as_str().to_string()),
        );
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct OpenAIError {
    pub error: OpenAIErrorDetail,
}

impl OpenAIError {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("error") {
            Some(field) if !field.is_null() => {
                result.error = OpenAIErrorDetail::from_json(field)?;
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert("error".to_string(), self.error.to_json());
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PollResponse {
    pub access_token: Option<String>,
    pub email: Option<String>,
    pub expires_in: Option<i64>,
    pub plan: Option<CliPlan>,
    pub refresh_token: Option<String>,
    pub status: PollStatus,
}

impl PollResponse {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("access_token") {
            Some(field) if !field.is_null() => {
                result.access_token = Some(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?
                        .to_string(),
                );
            }
            _ => {}
        }
        match object.get("email") {
            Some(field) if !field.is_null() => {
                result.email = Some(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?
                        .to_string(),
                );
            }
            _ => {}
        }
        match object.get("expires_in") {
            Some(field) if !field.is_null() => {
                result.expires_in = Some(
                    field
                        .as_i64()
                        .ok_or_else(|| "expected an integer".to_string())?,
                );
            }
            _ => {}
        }
        match object.get("plan") {
            Some(field) if !field.is_null() => {
                result.plan = Some(CliPlan::parse(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?,
                )?);
            }
            _ => {}
        }
        match object.get("refresh_token") {
            Some(field) if !field.is_null() => {
                result.refresh_token = Some(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?
                        .to_string(),
                );
            }
            _ => {}
        }
        match object.get("status") {
            Some(field) if !field.is_null() => {
                result.status = PollStatus::parse(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?,
                )?;
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        if let Some(item) = &self.access_token {
            map.insert("access_token".to_string(), Value::String(item.clone()));
        }
        if let Some(item) = &self.email {
            map.insert("email".to_string(), Value::String(item.clone()));
        }
        if let Some(item) = &self.expires_in {
            map.insert("expires_in".to_string(), Value::from(*item));
        }
        if let Some(item) = &self.plan {
            map.insert("plan".to_string(), Value::String(item.as_str().to_string()));
        }
        if let Some(item) = &self.refresh_token {
            map.insert("refresh_token".to_string(), Value::String(item.clone()));
        }
        map.insert(
            "status".to_string(),
            Value::String(self.status.as_str().to_string()),
        );
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct UsageRequestRecord {
    pub api_key_id: Option<String>,
    pub cached_tokens: i64,
    pub completion_tokens: i64,
    pub cost_micros: i64,
    pub error_code: Option<String>,
    pub finish_reason: Option<String>,
    pub max_tokens_granted: Option<i64>,
    pub max_tokens_requested: Option<i64>,
    pub model: String,
    pub noncached_prompt_tokens: i64,
    pub pricing_version: String,
    pub prompt_tokens: i64,
    pub provider: Option<UsageProvider>,
    pub reasoning_tokens: i64,
    pub recorded_at: String,
    pub request_id: String,
    pub response_request_id: Option<String>,
    pub status_code: i64,
    pub stream: bool,
    pub tpot_ms: Option<i64>,
    pub ts_end: Option<String>,
    pub ts_start: String,
    pub ttft_ms: Option<i64>,
}

impl UsageRequestRecord {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("api_key_id") {
            Some(field) if !field.is_null() => {
                result.api_key_id = Some(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?
                        .to_string(),
                );
            }
            _ => {}
        }
        match object.get("cached_tokens") {
            Some(field) if !field.is_null() => {
                result.cached_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("completion_tokens") {
            Some(field) if !field.is_null() => {
                result.completion_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("cost_micros") {
            Some(field) if !field.is_null() => {
                result.cost_micros = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("error_code") {
            Some(field) if !field.is_null() => {
                result.error_code = Some(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?
                        .to_string(),
                );
            }
            _ => {}
        }
        match object.get("finish_reason") {
            Some(field) if !field.is_null() => {
                result.finish_reason = Some(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?
                        .to_string(),
                );
            }
            _ => {}
        }
        match object.get("max_tokens_granted") {
            Some(field) if !field.is_null() => {
                result.max_tokens_granted = Some(
                    field
                        .as_i64()
                        .ok_or_else(|| "expected an integer".to_string())?,
                );
            }
            _ => {}
        }
        match object.get("max_tokens_requested") {
            Some(field) if !field.is_null() => {
                result.max_tokens_requested = Some(
                    field
                        .as_i64()
                        .ok_or_else(|| "expected an integer".to_string())?,
                );
            }
            _ => {}
        }
        match object.get("model") {
            Some(field) if !field.is_null() => {
                result.model = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("noncached_prompt_tokens") {
            Some(field) if !field.is_null() => {
                result.noncached_prompt_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("pricing_version") {
            Some(field) if !field.is_null() => {
                result.pricing_version = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("prompt_tokens") {
            Some(field) if !field.is_null() => {
                result.prompt_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("provider") {
            Some(field) if !field.is_null() => {
                result.provider = Some(UsageProvider::parse(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?,
                )?);
            }
            _ => {}
        }
        match object.get("reasoning_tokens") {
            Some(field) if !field.is_null() => {
                result.reasoning_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("recorded_at") {
            Some(field) if !field.is_null() => {
                result.recorded_at = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("request_id") {
            Some(field) if !field.is_null() => {
                result.request_id = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("response_request_id") {
            Some(field) if !field.is_null() => {
                result.response_request_id = Some(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?
                        .to_string(),
                );
            }
            _ => {}
        }
        match object.get("status_code") {
            Some(field) if !field.is_null() => {
                result.status_code = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("stream") {
            Some(field) if !field.is_null() => {
                result.stream = field
                    .as_bool()
                    .ok_or_else(|| "expected a boolean".to_string())?;
            }
            _ => {}
        }
        match object.get("tpot_ms") {
            Some(field) if !field.is_null() => {
                result.tpot_ms = Some(
                    field
                        .as_i64()
                        .ok_or_else(|| "expected an integer".to_string())?,
                );
            }
            _ => {}
        }
        match object.get("ts_end") {
            Some(field) if !field.is_null() => {
                result.ts_end = Some(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?
                        .to_string(),
                );
            }
            _ => {}
        }
        match object.get("ts_start") {
            Some(field) if !field.is_null() => {
                result.ts_start = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("ttft_ms") {
            Some(field) if !field.is_null() => {
                result.ttft_ms = Some(
                    field
                        .as_i64()
                        .ok_or_else(|| "expected an integer".to_string())?,
                );
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        if let Some(item) = &self.api_key_id {
            map.insert("api_key_id".to_string(), Value::String(item.clone()));
        }
        map.insert("cached_tokens".to_string(), Value::from(self.cached_tokens));
        map.insert(
            "completion_tokens".to_string(),
            Value::from(self.completion_tokens),
        );
        map.insert("cost_micros".to_string(), Value::from(self.cost_micros));
        if let Some(item) = &self.error_code {
            map.insert("error_code".to_string(), Value::String(item.clone()));
        }
        if let Some(item) = &self.finish_reason {
            map.insert("finish_reason".to_string(), Value::String(item.clone()));
        }
        if let Some(item) = &self.max_tokens_granted {
            map.insert("max_tokens_granted".to_string(), Value::from(*item));
        }
        if let Some(item) = &self.max_tokens_requested {
            map.insert("max_tokens_requested".to_string(), Value::from(*item));
        }
        map.insert("model".to_string(), Value::String(self.model.clone()));
        map.insert(
            "noncached_prompt_tokens".to_string(),
            Value::from(self.noncached_prompt_tokens),
        );
        map.insert(
            "pricing_version".to_string(),
            Value::String(self.pricing_version.clone()),
        );
        map.insert("prompt_tokens".to_string(), Value::from(self.prompt_tokens));
        if let Some(item) = &self.provider {
            map.insert(
                "provider".to_string(),
                Value::String(item.as_str().to_string()),
            );
        }
        map.insert(
            "reasoning_tokens".to_string(),
            Value::from(self.reasoning_tokens),
        );
        map.insert(
            "recorded_at".to_string(),
            Value::String(self.recorded_at.clone()),
        );
        map.insert(
            "request_id".to_string(),
            Value::String(self.request_id.clone()),
        );
        if let Some(item) = &self.response_request_id {
            map.insert(
                "response_request_id".to_string(),
                Value::String(item.clone()),
            );
        }
        map.insert("status_code".to_string(), Value::from(self.status_code));
        map.insert("stream".to_string(), Value::Bool(self.stream));
        if let Some(item) = &self.tpot_ms {
            map.insert("tpot_ms".to_string(), Value::from(*item));
        }
        if let Some(item) = &self.ts_end {
            map.insert("ts_end".to_string(), Value::String(item.clone()));
        }
        map.insert("ts_start".to_string(), Value::String(self.ts_start.clone()));
        if let Some(item) = &self.ttft_ms {
            map.insert("ttft_ms".to_string(), Value::from(*item));
        }
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct UsageRequestTotals {
    pub cached_tokens: i64,
    pub completion_tokens: i64,
    pub cost_micros: i64,
    pub noncached_prompt_tokens: i64,
    pub prompt_tokens: i64,
    pub reasoning_tokens: i64,
    pub requests: i64,
}

impl UsageRequestTotals {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("cached_tokens") {
            Some(field) if !field.is_null() => {
                result.cached_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("completion_tokens") {
            Some(field) if !field.is_null() => {
                result.completion_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("cost_micros") {
            Some(field) if !field.is_null() => {
                result.cost_micros = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("noncached_prompt_tokens") {
            Some(field) if !field.is_null() => {
                result.noncached_prompt_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("prompt_tokens") {
            Some(field) if !field.is_null() => {
                result.prompt_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("reasoning_tokens") {
            Some(field) if !field.is_null() => {
                result.reasoning_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("requests") {
            Some(field) if !field.is_null() => {
                result.requests = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert("cached_tokens".to_string(), Value::from(self.cached_tokens));
        map.insert(
            "completion_tokens".to_string(),
            Value::from(self.completion_tokens),
        );
        map.insert("cost_micros".to_string(), Value::from(self.cost_micros));
        map.insert(
            "noncached_prompt_tokens".to_string(),
            Value::from(self.noncached_prompt_tokens),
        );
        map.insert("prompt_tokens".to_string(), Value::from(self.prompt_tokens));
        map.insert(
            "reasoning_tokens".to_string(),
            Value::from(self.reasoning_tokens),
        );
        map.insert("requests".to_string(), Value::from(self.requests));
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct UsageRequestPage {
    pub as_of: String,
    pub next_cursor: Option<String>,
    pub requests: Vec<UsageRequestRecord>,
    pub totals: UsageRequestTotals,
}

impl UsageRequestPage {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("as_of") {
            Some(field) if !field.is_null() => {
                result.as_of = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("next_cursor") {
            Some(field) if !field.is_null() => {
                result.next_cursor = Some(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?
                        .to_string(),
                );
            }
            _ => {}
        }
        match object.get("requests") {
            Some(field) if !field.is_null() => {
                result.requests = {
                    let array = field
                        .as_array()
                        .ok_or_else(|| "expected an array".to_string())?;
                    let mut items = Vec::with_capacity(array.len());
                    for item in array {
                        items.push(UsageRequestRecord::from_json(item)?);
                    }
                    items
                };
            }
            _ => {}
        }
        match object.get("totals") {
            Some(field) if !field.is_null() => {
                result.totals = UsageRequestTotals::from_json(field)?;
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert("as_of".to_string(), Value::String(self.as_of.clone()));
        if let Some(item) = &self.next_cursor {
            map.insert("next_cursor".to_string(), Value::String(item.clone()));
        }
        map.insert(
            "requests".to_string(),
            Value::Array(self.requests.iter().map(|item| item.to_json()).collect()),
        );
        map.insert("totals".to_string(), self.totals.to_json());
        Value::Object(map)
    }
}
