// Generated by contracts/generate_console_binding.py from
// contracts/wally-decisions-public-v1.openapi.json. DO NOT EDIT.
//
// Typed request and response models for the CLI's control-plane calls, so
// console.rs neither builds a request body by hand nor reads a response
// field by name. Regenerate and commit whenever the pinned contract moves.
#![allow(clippy::all)]

use serde_json::Value;
use std::collections::BTreeMap;

/// SHA-256 of contracts/wally-decisions-public-v1.openapi.json this file was built from.
pub const CONTRACT_SHA256: &str =
    "5f2f3a01039a611c3fb77e6f6e7cb5b309abbd9ff025329625605ce362ae2541";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ErrorCode {
    #[default]
    KBadRequest,
    KNotFound,
    KPayloadTooLarge,
    KUnprocessable,
    KInvalidApiKey,
    KExpiredApiKey,
    KRevokedApiKey,
    KInsufficientCredit,
    KAccountFrozen,
    KModelNotEntitled,
    KNotInCohort,
    KUserRateLimited,
    KRequestCancelled,
    KQuotaExceeded,
    KCapacityExceeded,
    KIdempotencyKeyReused,
    KUnsupportedEndpoint,
    KProxyRetired,
    KGatewayUnavailable,
    KControlPlaneOverloaded,
    KCreditGateUnavailable,
    KUpstreamContractViolation,
    KUnattributedKey,
    KInternal,
    KBadGateway,
    KDraining,
    KSpoolUnhealthy,
    KCold,
    KTimeout,
}

impl ErrorCode {
    pub fn as_str(&self) -> &'static str {
        match self {
            ErrorCode::KBadRequest => "bad_request",
            ErrorCode::KNotFound => "not_found",
            ErrorCode::KPayloadTooLarge => "payload_too_large",
            ErrorCode::KUnprocessable => "unprocessable",
            ErrorCode::KInvalidApiKey => "invalid_api_key",
            ErrorCode::KExpiredApiKey => "expired_api_key",
            ErrorCode::KRevokedApiKey => "revoked_api_key",
            ErrorCode::KInsufficientCredit => "insufficient_credit",
            ErrorCode::KAccountFrozen => "account_frozen",
            ErrorCode::KModelNotEntitled => "model_not_entitled",
            ErrorCode::KNotInCohort => "not_in_cohort",
            ErrorCode::KUserRateLimited => "user_rate_limited",
            ErrorCode::KRequestCancelled => "request_cancelled",
            ErrorCode::KQuotaExceeded => "quota_exceeded",
            ErrorCode::KCapacityExceeded => "capacity_exceeded",
            ErrorCode::KIdempotencyKeyReused => "idempotency_key_reused",
            ErrorCode::KUnsupportedEndpoint => "unsupported_endpoint",
            ErrorCode::KProxyRetired => "proxy_retired",
            ErrorCode::KGatewayUnavailable => "gateway_unavailable",
            ErrorCode::KControlPlaneOverloaded => "control_plane_overloaded",
            ErrorCode::KCreditGateUnavailable => "credit_gate_unavailable",
            ErrorCode::KUpstreamContractViolation => "upstream_contract_violation",
            ErrorCode::KUnattributedKey => "unattributed_key",
            ErrorCode::KInternal => "internal",
            ErrorCode::KBadGateway => "bad_gateway",
            ErrorCode::KDraining => "draining",
            ErrorCode::KSpoolUnhealthy => "spool_unhealthy",
            ErrorCode::KCold => "cold",
            ErrorCode::KTimeout => "timeout",
        }
    }

    pub fn parse(raw: &str) -> Result<Self, String> {
        match raw {
            "bad_request" => Ok(ErrorCode::KBadRequest),
            "not_found" => Ok(ErrorCode::KNotFound),
            "payload_too_large" => Ok(ErrorCode::KPayloadTooLarge),
            "unprocessable" => Ok(ErrorCode::KUnprocessable),
            "invalid_api_key" => Ok(ErrorCode::KInvalidApiKey),
            "expired_api_key" => Ok(ErrorCode::KExpiredApiKey),
            "revoked_api_key" => Ok(ErrorCode::KRevokedApiKey),
            "insufficient_credit" => Ok(ErrorCode::KInsufficientCredit),
            "account_frozen" => Ok(ErrorCode::KAccountFrozen),
            "model_not_entitled" => Ok(ErrorCode::KModelNotEntitled),
            "not_in_cohort" => Ok(ErrorCode::KNotInCohort),
            "user_rate_limited" => Ok(ErrorCode::KUserRateLimited),
            "request_cancelled" => Ok(ErrorCode::KRequestCancelled),
            "quota_exceeded" => Ok(ErrorCode::KQuotaExceeded),
            "capacity_exceeded" => Ok(ErrorCode::KCapacityExceeded),
            "idempotency_key_reused" => Ok(ErrorCode::KIdempotencyKeyReused),
            "unsupported_endpoint" => Ok(ErrorCode::KUnsupportedEndpoint),
            "proxy_retired" => Ok(ErrorCode::KProxyRetired),
            "gateway_unavailable" => Ok(ErrorCode::KGatewayUnavailable),
            "control_plane_overloaded" => Ok(ErrorCode::KControlPlaneOverloaded),
            "credit_gate_unavailable" => Ok(ErrorCode::KCreditGateUnavailable),
            "upstream_contract_violation" => Ok(ErrorCode::KUpstreamContractViolation),
            "unattributed_key" => Ok(ErrorCode::KUnattributedKey),
            "internal" => Ok(ErrorCode::KInternal),
            "bad_gateway" => Ok(ErrorCode::KBadGateway),
            "draining" => Ok(ErrorCode::KDraining),
            "spool_unhealthy" => Ok(ErrorCode::KSpoolUnhealthy),
            "cold" => Ok(ErrorCode::KCold),
            "timeout" => Ok(ErrorCode::KTimeout),
            other => Err(format!("unknown ErrorCode: {other}")),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ErrorType {
    #[default]
    KInvalidRequestError,
    KAuthenticationError,
    KPermissionError,
    KRateLimitError,
    KQuota,
    KCapacity,
    KServerError,
    KTimeout,
}

impl ErrorType {
    pub fn as_str(&self) -> &'static str {
        match self {
            ErrorType::KInvalidRequestError => "invalid_request_error",
            ErrorType::KAuthenticationError => "authentication_error",
            ErrorType::KPermissionError => "permission_error",
            ErrorType::KRateLimitError => "rate_limit_error",
            ErrorType::KQuota => "quota",
            ErrorType::KCapacity => "capacity",
            ErrorType::KServerError => "server_error",
            ErrorType::KTimeout => "timeout",
        }
    }

    pub fn parse(raw: &str) -> Result<Self, String> {
        match raw {
            "invalid_request_error" => Ok(ErrorType::KInvalidRequestError),
            "authentication_error" => Ok(ErrorType::KAuthenticationError),
            "permission_error" => Ok(ErrorType::KPermissionError),
            "rate_limit_error" => Ok(ErrorType::KRateLimitError),
            "quota" => Ok(ErrorType::KQuota),
            "capacity" => Ok(ErrorType::KCapacity),
            "server_error" => Ok(ErrorType::KServerError),
            "timeout" => Ok(ErrorType::KTimeout),
            other => Err(format!("unknown ErrorType: {other}")),
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DecisionOption {
    pub description: Option<String>,
    pub name: String,
}

impl DecisionOption {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("description") {
            Some(field) if !field.is_null() => {
                result.description = Some(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?
                        .to_string(),
                );
            }
            _ => {}
        }
        match object.get("name") {
            Some(field) if !field.is_null() => {
                result.name = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        if let Some(item) = &self.description {
            map.insert("description".to_string(), Value::String(item.clone()));
        }
        map.insert("name".to_string(), Value::String(self.name.clone()));
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ChoiceQuestion {
    pub id: String,
    pub options: Vec<DecisionOption>,
    pub question: String,
    pub r#type: String,
}

impl ChoiceQuestion {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("id") {
            Some(field) if !field.is_null() => {
                result.id = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("options") {
            Some(field) if !field.is_null() => {
                result.options = {
                    let array = field
                        .as_array()
                        .ok_or_else(|| "expected an array".to_string())?;
                    let mut items = Vec::with_capacity(array.len());
                    for item in array {
                        items.push(DecisionOption::from_json(item)?);
                    }
                    items
                };
            }
            _ => {}
        }
        match object.get("question") {
            Some(field) if !field.is_null() => {
                result.question = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("type") {
            Some(field) if !field.is_null() => {
                result.r#type = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert("id".to_string(), Value::String(self.id.clone()));
        map.insert(
            "options".to_string(),
            Value::Array(self.options.iter().map(|item| item.to_json()).collect()),
        );
        map.insert("question".to_string(), Value::String(self.question.clone()));
        map.insert("type".to_string(), Value::String(self.r#type.clone()));
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct LabelProbabilities(pub BTreeMap<String, f64>);

impl LabelProbabilities {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        Ok(Self({
            let object = value
                .as_object()
                .ok_or_else(|| "expected an object".to_string())?;
            let mut items = BTreeMap::new();
            for (key, item) in object {
                items.insert(
                    key.clone(),
                    item.as_f64()
                        .ok_or_else(|| "expected a number".to_string())?,
                );
            }
            items
        }))
    }
    pub fn to_json(&self) -> Value {
        Value::Object(
            self.0
                .iter()
                .map(|(key, item)| (key.clone(), Value::from(*item)))
                .collect(),
        )
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DecisionAnswer {
    pub choice: Option<String>,
    pub label_mass: f64,
    pub probabilities: LabelProbabilities,
    pub score: Option<f64>,
    pub r#type: String,
}

impl DecisionAnswer {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("choice") {
            Some(field) if !field.is_null() => {
                result.choice = Some(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?
                        .to_string(),
                );
            }
            _ => {}
        }
        match object.get("label_mass") {
            Some(field) if !field.is_null() => {
                result.label_mass = field
                    .as_f64()
                    .ok_or_else(|| "expected a number".to_string())?;
            }
            _ => {}
        }
        match object.get("probabilities") {
            Some(field) if !field.is_null() => {
                result.probabilities = LabelProbabilities::from_json(field)?;
            }
            _ => {}
        }
        match object.get("score") {
            Some(field) if !field.is_null() => {
                result.score = Some(
                    field
                        .as_f64()
                        .ok_or_else(|| "expected a number".to_string())?,
                );
            }
            _ => {}
        }
        match object.get("type") {
            Some(field) if !field.is_null() => {
                result.r#type = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        if let Some(item) = &self.choice {
            map.insert("choice".to_string(), Value::String(item.clone()));
        }
        map.insert("label_mass".to_string(), Value::from(self.label_mass));
        map.insert("probabilities".to_string(), self.probabilities.to_json());
        if let Some(item) = &self.score {
            map.insert("score".to_string(), Value::from(*item));
        }
        map.insert("type".to_string(), Value::String(self.r#type.clone()));
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DecisionAnswers(pub BTreeMap<String, DecisionAnswer>);

impl DecisionAnswers {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        Ok(Self({
            let object = value
                .as_object()
                .ok_or_else(|| "expected an object".to_string())?;
            let mut items = BTreeMap::new();
            for (key, item) in object {
                items.insert(key.clone(), DecisionAnswer::from_json(item)?);
            }
            items
        }))
    }
    pub fn to_json(&self) -> Value {
        Value::Object(
            self.0
                .iter()
                .map(|(key, item)| (key.clone(), item.to_json()))
                .collect(),
        )
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ScoreQuestion {
    pub id: String,
    pub levels: Vec<String>,
    pub question: String,
    pub r#type: String,
}

impl ScoreQuestion {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("id") {
            Some(field) if !field.is_null() => {
                result.id = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("levels") {
            Some(field) if !field.is_null() => {
                result.levels = {
                    let array = field
                        .as_array()
                        .ok_or_else(|| "expected an array".to_string())?;
                    let mut items = Vec::with_capacity(array.len());
                    for item in array {
                        items.push(
                            item.as_str()
                                .ok_or_else(|| "expected a string".to_string())?
                                .to_string(),
                        );
                    }
                    items
                };
            }
            _ => {}
        }
        match object.get("question") {
            Some(field) if !field.is_null() => {
                result.question = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("type") {
            Some(field) if !field.is_null() => {
                result.r#type = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert("id".to_string(), Value::String(self.id.clone()));
        map.insert(
            "levels".to_string(),
            Value::Array(
                self.levels
                    .iter()
                    .map(|item| Value::String(item.clone()))
                    .collect(),
            ),
        );
        map.insert("question".to_string(), Value::String(self.question.clone()));
        map.insert("type".to_string(), Value::String(self.r#type.clone()));
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct YesNoQuestion {
    pub id: String,
    pub no: Option<String>,
    pub question: String,
    pub r#type: String,
    pub yes: Option<String>,
}

impl YesNoQuestion {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("id") {
            Some(field) if !field.is_null() => {
                result.id = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("no") {
            Some(field) if !field.is_null() => {
                result.no = Some(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?
                        .to_string(),
                );
            }
            _ => {}
        }
        match object.get("question") {
            Some(field) if !field.is_null() => {
                result.question = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("type") {
            Some(field) if !field.is_null() => {
                result.r#type = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("yes") {
            Some(field) if !field.is_null() => {
                result.yes = Some(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?
                        .to_string(),
                );
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert("id".to_string(), Value::String(self.id.clone()));
        if let Some(item) = &self.no {
            map.insert("no".to_string(), Value::String(item.clone()));
        }
        map.insert("question".to_string(), Value::String(self.question.clone()));
        map.insert("type".to_string(), Value::String(self.r#type.clone()));
        if let Some(item) = &self.yes {
            map.insert("yes".to_string(), Value::String(item.clone()));
        }
        Value::Object(map)
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum DecisionQuestion {
    ChoiceQuestion(ChoiceQuestion),
    ScoreQuestion(ScoreQuestion),
    YesNoQuestion(YesNoQuestion),
}

impl Default for DecisionQuestion {
    fn default() -> Self {
        Self::ChoiceQuestion(ChoiceQuestion::default())
    }
}

impl DecisionQuestion {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let kind = value
            .get("type")
            .and_then(Value::as_str)
            .ok_or_else(|| "missing discriminator type".to_string())?;
        match kind {
            "choice" => Ok(Self::ChoiceQuestion(ChoiceQuestion::from_json(value)?)),
            "score" => Ok(Self::ScoreQuestion(ScoreQuestion::from_json(value)?)),
            "yes_no" => Ok(Self::YesNoQuestion(YesNoQuestion::from_json(value)?)),
            other => Err(format!("unknown DecisionQuestion discriminator: {other}")),
        }
    }

    pub fn to_json(&self) -> Value {
        match self {
            Self::ChoiceQuestion(value) => value.to_json(),
            Self::ScoreQuestion(value) => value.to_json(),
            Self::YesNoQuestion(value) => value.to_json(),
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DecisionUsage {
    pub completion_tokens: i64,
    pub prompt_tokens: i64,
    pub reasoning_tokens: Option<i64>,
    pub total_tokens: i64,
}

impl DecisionUsage {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("completion_tokens") {
            Some(field) if !field.is_null() => {
                result.completion_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("prompt_tokens") {
            Some(field) if !field.is_null() => {
                result.prompt_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("reasoning_tokens") {
            Some(field) if !field.is_null() => {
                result.reasoning_tokens = Some(
                    field
                        .as_i64()
                        .ok_or_else(|| "expected an integer".to_string())?,
                );
            }
            _ => {}
        }
        match object.get("total_tokens") {
            Some(field) if !field.is_null() => {
                result.total_tokens = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert(
            "completion_tokens".to_string(),
            Value::from(self.completion_tokens),
        );
        map.insert("prompt_tokens".to_string(), Value::from(self.prompt_tokens));
        if let Some(item) = &self.reasoning_tokens {
            map.insert("reasoning_tokens".to_string(), Value::from(*item));
        }
        map.insert("total_tokens".to_string(), Value::from(self.total_tokens));
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DecisionsRequest {
    pub input: String,
    pub model: String,
    pub prompt_format_version: Option<i64>,
    pub questions: Vec<DecisionQuestion>,
    pub temperature: Option<f64>,
}

impl DecisionsRequest {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("input") {
            Some(field) if !field.is_null() => {
                result.input = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("model") {
            Some(field) if !field.is_null() => {
                result.model = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("prompt_format_version") {
            Some(field) if !field.is_null() => {
                result.prompt_format_version = Some(
                    field
                        .as_i64()
                        .ok_or_else(|| "expected an integer".to_string())?,
                );
            }
            _ => {}
        }
        match object.get("questions") {
            Some(field) if !field.is_null() => {
                result.questions = {
                    let array = field
                        .as_array()
                        .ok_or_else(|| "expected an array".to_string())?;
                    let mut items = Vec::with_capacity(array.len());
                    for item in array {
                        items.push(DecisionQuestion::from_json(item)?);
                    }
                    items
                };
            }
            _ => {}
        }
        match object.get("temperature") {
            Some(field) if !field.is_null() => {
                result.temperature = Some(
                    field
                        .as_f64()
                        .ok_or_else(|| "expected a number".to_string())?,
                );
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert("input".to_string(), Value::String(self.input.clone()));
        map.insert("model".to_string(), Value::String(self.model.clone()));
        if let Some(item) = &self.prompt_format_version {
            map.insert("prompt_format_version".to_string(), Value::from(*item));
        }
        map.insert(
            "questions".to_string(),
            Value::Array(self.questions.iter().map(|item| item.to_json()).collect()),
        );
        if let Some(item) = &self.temperature {
            map.insert("temperature".to_string(), Value::from(*item));
        }
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DecisionsResponse {
    pub answers: DecisionAnswers,
    pub model: String,
    pub object: String,
    pub prompt_format_version: i64,
    pub usage: DecisionUsage,
}

impl DecisionsResponse {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("answers") {
            Some(field) if !field.is_null() => {
                result.answers = DecisionAnswers::from_json(field)?;
            }
            _ => {}
        }
        match object.get("model") {
            Some(field) if !field.is_null() => {
                result.model = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("object") {
            Some(field) if !field.is_null() => {
                result.object = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("prompt_format_version") {
            Some(field) if !field.is_null() => {
                result.prompt_format_version = field
                    .as_i64()
                    .ok_or_else(|| "expected an integer".to_string())?;
            }
            _ => {}
        }
        match object.get("usage") {
            Some(field) if !field.is_null() => {
                result.usage = DecisionUsage::from_json(field)?;
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert("answers".to_string(), self.answers.to_json());
        map.insert("model".to_string(), Value::String(self.model.clone()));
        map.insert("object".to_string(), Value::String(self.object.clone()));
        map.insert(
            "prompt_format_version".to_string(),
            Value::from(self.prompt_format_version),
        );
        map.insert("usage".to_string(), self.usage.to_json());
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct OpenAIErrorDetail {
    pub code: Option<ErrorCode>,
    pub message: String,
    pub param: Option<String>,
    pub r#type: ErrorType,
}

impl OpenAIErrorDetail {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("code") {
            Some(field) if !field.is_null() => {
                result.code = Some(ErrorCode::parse(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?,
                )?);
            }
            _ => {}
        }
        match object.get("message") {
            Some(field) if !field.is_null() => {
                result.message = field
                    .as_str()
                    .ok_or_else(|| "expected a string".to_string())?
                    .to_string();
            }
            _ => {}
        }
        match object.get("param") {
            Some(field) if !field.is_null() => {
                result.param = Some(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?
                        .to_string(),
                );
            }
            _ => {}
        }
        match object.get("type") {
            Some(field) if !field.is_null() => {
                result.r#type = ErrorType::parse(
                    field
                        .as_str()
                        .ok_or_else(|| "expected a string".to_string())?,
                )?;
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        if let Some(item) = &self.code {
            map.insert("code".to_string(), Value::String(item.as_str().to_string()));
        }
        map.insert("message".to_string(), Value::String(self.message.clone()));
        if let Some(item) = &self.param {
            map.insert("param".to_string(), Value::String(item.clone()));
        }
        map.insert(
            "type".to_string(),
            Value::String(self.r#type.as_str().to_string()),
        );
        Value::Object(map)
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct OpenAIError {
    pub error: OpenAIErrorDetail,
}

impl OpenAIError {
    pub fn from_json(value: &Value) -> Result<Self, String> {
        let object = value
            .as_object()
            .ok_or_else(|| "expected a JSON object".to_string())?;
        let mut result = Self::default();
        match object.get("error") {
            Some(field) if !field.is_null() => {
                result.error = OpenAIErrorDetail::from_json(field)?;
            }
            _ => {}
        }
        Ok(result)
    }

    pub fn to_json(&self) -> Value {
        let mut map = serde_json::Map::new();
        map.insert("error".to_string(), self.error.to_json());
        Value::Object(map)
    }
}
